sonic-net/sonic-platform-daemons

Dockerfile

redis-tools package depends on libjemalloc1

Install libjemalloc1

---

Dockerfile

This reverts commit 73b5fcee2840adcc64bee5e6ffb226a9928959e4.
libjemalloc1 will be installed directly to orchagent and database

Revert "Install libjemalloc1 (#1)"

---

sonic-ledd/scripts/ledd

sonic-ledd/scripts/ledd: Remove redundacies
Previous implementation of front-panel LED controls has a lot of
redundancies that are unnecessary for what it currently does. It would
always set all front-panel LEDs to off, populate a dictionary, then
iterate through the dictionary to turn LEDs to correct colors. LEDs can
simply be set through one iteration.
In normal SONiC it was already noticeable (LEDs flash off for a brief
moment every second) but for SONiC+cEOS it is much worse since
turning on or off LEDs takes a much longer amount of time.
This problem was found by internal product tests testing SONiC+cEOS.
Signed-off-by: Zhi Yuan Zhao zyzhao@arista.com

Remove redundancy in ledd

---

sonic-ledd/scripts/ledd

Not all platforms rely on ledd to control front-panel LEDs. These platforms purposefully do not provide a led_control.py plugin. Currently, ledd is started unconditionally, therefore it should not exit with a non-zero exit code if it fails to find a platform-specific led_control.py plugin.
However, ledd will log a message to syslog before exiting, thus we will be able to trace down an unexpected missing led_control.py file if the situation ever arises.

[ledd] Exit with code 0 if we fail to find a platform-specific led_control module

---

sonic-ledd/scripts/ledd

Otherwise ledd ignores signals other than SIGKILL making impossible to
use \_\_del__() destructors in LedClass implementations and delays pmon
docker container shutdown up to 10s.
Here is output from /var/log/supervisor/supervisord.log after
"systemctl stop pmon":
2018-05-26 10:40:36,323 WARN received SIGTERM indicating exit request
2018-05-26 10:40:36,323 INFO waiting for rsyslogd, ledd to die
2018-05-26 10:40:39,327 INFO waiting for rsyslogd, ledd to die
2018-05-26 10:40:42,330 INFO waiting for rsyslogd, ledd to die
2018-05-26 10:40:45,335 INFO waiting for rsyslogd, ledd to die
Note that according to docker-stop(1) default time to wait before retry
with KILL signal is 10s.
Steps to reproduce:
\# docker exec -ti pmon bash
\# kill -TERM $(pgrep ledd)
\# kill -INT $(pgrep ledd)
\# kill -0 …

[ledd] Use select() with timeout for AppDB notifications

---

sonic-xcvrd/scripts/xcvrd
sonic-xcvrd/setup.py

[sonic-xcvrd] add new daemon sonic-xcvrd to fetch Transceiver informations to DB
* This new daemon will periodcally read DOM information from eeprom and post to DB
* This new daemon will listen to the SFP plug in/out event and update the DB accordingly
* file change list
new file:   scripts/xcvrd
new file:   setup.py
Design doc: https://github.com/Azure/SONiC/blob/gh-pages/doc/OIDsforSensorandTransciver.MD

[sonic-xcvrd] add new daemon sonic-xcvrd to platform monitor

---

sonic-xcvrd/scripts/xcvrd

Enhanced xcvrd with following modification:
1. get hwsku from DB instead from minigraph, to avoid failure in the case that no minigraph exist.
2. before access the SFP eeprom, determine the presence the SFP, to avoid error log from kernel when accessing a non-existence SFP eeprom on some platform

[sonic-xcvrd] sonic-xcvrd enhancement

---

sonic-psud/scripts/psud
sonic-psud/setup.py

* This new daemon will periodcally read PSU presence and status from sysfs and write to DB
* CLI will get the PSU presence and status from DB directly.
Signed-off-by: Kevin Wang <kevinw@mellanox.com>

[sonic-psud] add a new daemon sonic-psud to platform monitor

---

sonic-ledd/scripts/ledd
sonic-psud/scripts/psud
sonic-xcvrd/scripts/xcvrd

Signed-off-by: Kevin Wang <kevinw@mellanox.com>

[sonic-platform-daemons] Refactor daemons based on DaemonBase class 

---

sonic-ledd/scripts/ledd
sonic-psud/scripts/psud
sonic-xcvrd/scripts/xcvrd

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
xcvrd shutdown flow is broken due to a platform_sfputil.get_transceiver_change_event() blocking call which uses epoll_wait. This function affects process signal mask and signal handlers are not getting called.
**- What I did**
* Fixed xcvrd shutdown flow
* Refactored xcvrd code base
* Aligned psud chassis key name with Spec
* Aligned psud with daemon base
* Refactored psud code base
* Aligned ledd with daemon base
* Refactored ledd code base
* Changed daemon architecture in order to use signal handlers properly
* Moved platform_sfputil.get_transceiver_change_event() blocking call to a separate process
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin
3. service pmon stop
4. …

Fixed xcvrd shutdown flow

---

sonic-xcvrd/scripts/xcvrd

**- What I did**
Dynamic transceiver tuning support
Dynamically program pre-emphasis and other settings based on media detected in xcvrd. The various supported media are defined in media_settings.json
Perform OIR of different media types. Dump the pre-emphasis values from hardware and verify that they got reflected
**- Description for the changelog**
Support for dynamically programming pre-emphasis
**- A picture of a cute animal (not mandatory but encouraged)**

Dynamic transceiver tuning support

---

sonic-xcvrd/scripts/xcvrd

Issue and fix description: 
- Currently, Xcvrd relies on the "PortConfigDone" flag to start to retrieve SFP info. But in some case, even the "PortConfigDone" flag set, not all the SFP devices are ready, so there could be some SFP info missed in the SFP info table due to the delay. 
-  Add a period SFP table integrity check and recover function can fix this issue.  Another benefit of this fix is that can make sure SFP table info always recovered in any case.
- What I did in this fix
- add a recover check function to check if all SFP info in the table, if not write it to the table.
- run this recover function in the main task each 60s

[xcvrd] Fix missing sfp info table entry issue 

---

sonic-xcvrd/scripts/xcvrd

This change is added to dump ChannelMonitor Threshold and Module Monitor Threshold values as part of DOM EEPROM dump output.
Added code change in sff8436.py,sfputilshow.py, xcvrd,  sfpshow .. etc
Verified the output in following optics
a) AVAGO
b) Finisar
c) DELL
Seeing the following issue of Values not getting dumped properly from day 1
Some channel monitor values are not displayed correctly.
Will raise a seperate issue for that.
Ethernet124: SFP EEPROM detected
Connector: MPOx12
Encoding: 64B66B
Extended Identifier: Power Class 1(1.5W max)
Extended RateSelect Compliance: QSFP+ Rate Select Version 1
Identifier: QSFP+ or later
Length OM3(2m): 50
Nominal Bit Rate(100Mbs): 103
Specification compliance:
10/40G Ethernet Compliance Code: 40GBASE-SR4
Vendor Date Code(YYYY-MM-DD Lot): 2010-09-01 …

sonic_xcvrd: Support for DOM Threshold values for EEPROM dump

---

sonic-syseepromd/scripts/syseepromd

In case of some fail "global name 'sys' is not defined" error logs are more visible then real error message
Example:
```
Jul 23 14:36:31.223795 cab18-2-switch2 INFO pmon#syseepromd: Starting up...
Jul 23 14:36:31.931699 cab18-2-switch2 ERR pmon#syseepromd: Failed to load eeprom utility: Failed to load platform module 'eeprom': [Errno 2] No such file or directory
Jul 23 14:36:31.931929 cab18-2-switch2 INFO pmon#supervisord: syseepromd Failed to load eeprom utility: Failed to load platform module 'eeprom': [Errno 2] No such file or directory
Jul 23 14:36:31.932004 cab18-2-switch2 INFO pmon#supervisord: syseepromd Traceback (most recent call last):
Jul 23 14:36:31.932004 cab18-2-switch2 INFO pmon#supervisord: syseepromd   File "/usr/bin/syseepromd", line 142, in <module>
Jul 23 …
```

Add missing import statemet

---

sonic-syseepromd/scripts/syseepromd

Support new platform api with plugin mode compatible.
In this PR, new platform api is supported in following steps:
1. initialization, load new-platform-api-based class eeprom or chassis for syseepromd and psud respectively, if failed then load old style plugin.
2. for each api, call new platform api, old style plugin is called if the former raised a NotImplementError; other Exceptions raised will be passed to caller without handling.
now only two APIs are called in syseepromd, update_eeprom_db and read_eeprom.
it depends on the [sonic-platform-common #48 add get_eeprom to Chassis for syseepromd to access](https://github.com/Azure/sonic-platform-common/pull/48)

[syseepromd] Support both new platform API and old platform plugins

---

sonic-psud/scripts/psud

Support new platform api with plugin mode compatible.
In this PR, new platform api is supported in following steps:
1. initialization, load new-platform-api-based class eeprom or chassis for syseepromd and psud respectively, if failed then load old style plugin.
2. for each api, call new platform api, old style plugin is called if the former raised a NotImplementError; other Exceptions raised will be passed to caller without handling.
Three APIs for psud, get_num_psus, get_presence and get_powergood_status.

[psud] Support both new platform API and old platform plugins

---

sonic-xcvrd/scripts/xcvrd

Support new platform api with plugin mode compatible.
In this PR, new platform api is supported in following steps:
1. Initialization, load new-platform-api-based class chassis, if failed then load old style plugin sfputilbase.
2. For each api, call new platform api, old style plugin is called if the former raised a NotImplementError; other Exceptions raised will be passed to caller without handling.
3. For the functions that only available in sfputilbase, a helper module has to be introduced to replace sfputilbase, because it is an abstract class and can't be instantiated independently.
This has been done in [[sonic_platform_base] support new-platform-api-based daemons #48](https://github.com/Azure/sonic-platform-common/pull/48)

[xcvrd] Support both new platform API and old platform plugins

---

sonic-xcvrd/scripts/xcvrd

backport PR #39 to 201811 branch.
this PR to enhance xcvrd to be more robust by handling the more new system-level event:
1. wait for a certain period on system_not_ready event to overcome race condition when xcvrd started but system not ready.
2. start to routing work on system_become_ready event, this event indicates that the system is ready for SFP change event report.
3. exit on system_fail event
4. make xcvrd handle signal correctly

[xcvrd] backport PR(#39) "Enhance xcvrd to handle new system level event/error" to 201811

---

sonic-xcvrd/scripts/xcvrd

**- What I did**
Fixing transceiver tuning issue where number of lanes equal to number of logical ports in a port. (Example 40G port with 4 lanes is in 4x10G mode)
Define a profile where number of lanes equal to number of logical ports and check if pre-emphasis gets programmed
**- Description for the changelog**
Handling transceiver tuning scenario when number of lanes in a port is equal to number of logical ports created
[preemp_ut.txt](https://github.com/Azure/sonic-platform-daemons/files/3478202/preemp_ut.txt)
**- A picture of a cute animal (not mandatory but encouraged)**

[xcvrd] Fix transceiver tuning issue

---

sonic-xcvrd/scripts/xcvrd

backport PR https://github.com/Azure/sonic-platform-daemons/pull/44 from master to 201811 branch
Enhance the state machine in order to overcome a possible platform temporarily fail/unavailable case
1. When receiving system_fail event under NORMAL state, it will transmit to INIT instead of exit directly
2. In INIT state will handle system_fail event as the same as system_not_ready event, try certain times,
if the system recovered then transmit to NORMAL state again, if not recovered in a certain period, then exit.
the benefit of this change is that when the system has error/failed temporarily,  xcvrd can survive and recover instead of exit directly, make to more tolerance to errors.

[201811 xcvrd] state machine enhancement

---

sonic-xcvrd/scripts/xcvrd

Enhance the state machine in order to overcome a possible platform temporarily fail/unavailable case
1. When receiving system_fail event under NORMAL state, it will transmit to INIT instead of exit directly
2. In INIT state will handle system_fail event as the same as system_not_ready event, try certain times,
if the system recovered then transmit to NORMAL state again, if not recovered in a certain period, then exit.
the benefit of this change is that when the system has error/failed temporarily,  xcvrd can survive and recover instead of exit directly, make to more tolerance to errors.

[xcvrd] state machine enhancement

---

sonic-xcvrd/scripts/xcvrd

In case some FP port is not in port_config.ini but platform plugin still iterates through all FP ports including this one, there will be an exception as follows:
INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 840, in task_worker
INFO pmon#supervisord: xcvrd     for logical_port in logical_port_list:
INFO pmon#supervisord: xcvrd TypeError: 'NoneType' object is not iterable
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

[xcvrd] Fixed SFP state update in case port is not in port_config.ini

---

sonic-xcvrd/scripts/xcvrd

**What I did:**
DOM related informations are not displayed in 2.0 supported platforms and returns the following error.
root@sonic:/home/admin# sfpshow -eeprom -d
…
…
File "/usr/bin/sfpshow", line 146, in format_dict_value_to_string
if dom_info_dict is not None and dom_info_dict[key] != 'N/A':
KeyError: 'rxpowerhighalarm'
**How I did:**
Used 2.0 DOM API in xcvrd to  fetch DOM related information.
**How to verify:**
Check "sfpshow eeprom -d" output after making the changes.

[xcvrd] Retrieve DOM info using platform API 2.0 if implemented

---

sonic-xcvrd/scripts/xcvrd

DOM threshold info is missing from DB because of function to fetch DOM threshold info "post_port_dom_threshold_info_to_db" is not called in "dom_info_update_task", and which will break CLI "show interface transceiver eeprom -d".
The fix is to add call to "post_port_dom_threshold_info_to_db" in "dom_info_update_task".
This fix should be included in the 201911 and bmtor branch.

Fix missing DOM threshold info from DB

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

1. Catch exception in every fan/thermal refresh loop to avoid exit loop too early
2. For absense fan, no need get its data from platform API
3. Add unit test for new code

[Mellanox] Fix thermal control bugs

---

sonic-xcvrd/scripts/xcvrd

Add SFP event handling logic to XCVRD, the main purpose is to stop accessing SFP EEPROM when some error event raised from SFP and which will block the EEPROM accessing.  Design refer to https://github.com/Azure/SONiC/pull/586
1. When receive the error event on some SFP, the related ports will be added to a new table which is to store the ports that on top of the error SFP, xcvrd will remove the DOM table and stop to update the DOM until SFP recovered from the error. This is done by checking the new table before reading the DOM, if ports in error status, DOM update will be skipped.
2. A plug in event received on the error SFP will be considered as this SFP is recovered from error status.
**This PR has a dependency on https://github.com/Azure/sonic-buildimage/pull/4365 and …

[xcvrd] Extend xcvrd with SFP error event handling

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

What I did:
1. Set led to red and trigger syslog when fan is broken
2. Add fan drawer information to redis database
3. Trigger a syslog when any fan is absence or broken to alert user that "Insufficient fan number"
How I verify:
Manual test and run platform regression

[thermalctld] add FAN led management in thermal control daemon

---

sonic-syseepromd/scripts/syseepromd

Why I did:
- Since the termination of the syseepromd will lead to the termination of the pmon.
What I did:
- Regularly try to update the eeprom data, instead of exiting the syseepromd directly when the update_eeprom_to_db return with failure.

[syseepromd] Prevent the syseepromd from termination

---

sonic-psud/scripts/psud
sonic-thermalctld/scripts/thermalctld

1. psud will change PSU led and thermalctld cannot detect the led status change, so it would be better to always get PSU led from platform API
2. there might be delay between set led color and it take effect
Always get led status from platform API.
Manual test.

[psud][thermalctld] Always get fan/PSU LED status from platform API to avoid status inconsistencies

---

sonic-psud/scripts/psud

System health feature requires PSU temperature and voltage information, need store them to database for host side use.
How I did?
Get temperature and voltage information from platform API and store them to database
How I verify?
Manual test and check redis database.

[psud] Store PSU temperature and voltage information to database

---

sonic-xcvrd/scripts/xcvrd

**- What I did**
Add support for QSFP-DD cable consist from 8 lanes.
Add a DB entry for 'Application advertisement" for CMIS cable type.
Check for Transceiver DB data with QSFP-DD cable.
Check 'show interfaces transceiver eeprom Ethernet#' output.
**- Previous command output (if the output of a command-line utility has changed)**
**- New command output (if the output of a command-line utility has changed)**

[xcvrd] Add support for QSFP-DD cables

---

sonic-xcvrd/scripts/xcvrd

In Python, the return value of `main()` is not automatically the exit code which gets presented to the OS. This patch will pass the  return value of `main()` to the OS as the exit code.

[201811][xcvrd] Return value of main() is returned as process exit code

---

sonic-pcied/scripts/pcied
sonic-pcied/setup.py

pcied will run in pmon container to monitor the pcie device status during run time.
It will update the state db with current pcie status so other monitoring service can read to alert any failure status.

Initial version of pcied

---

sonic-xcvrd/scripts/xcvrd

Currently when there is an error event in xcvrd within SFP state machine, it returns with 0 exit code. With this change the SFP if it has an error event with return with non-zero exit code.

[xcvrd] Return non-zero error code on SFP error

---

sonic-thermalctld/scripts/thermalctld

Signed-off-by: Shlomi Bitton <shlomibi@mellanox.com>
**- Why I did it**
When a fan is under\over speed, status should change to 'Not OK' along with red LED color.
Changed the DB 'status' information to consider under\over fan speed.
run 'show platform fan' command.
**- Which release branch to backport (provide reason below if seleted)**
**- Description for the changelog**
**- A picture of a cute animal (not mandatory but encouraged)**

[Thermal] Fix for 'show platform fan' command

---

sonic-xcvrd/scripts/xcvrd

Merge of QSFP-DD support via PR# https://github.com/Azure/sonic-platform-daemons/pull/66
is making xcvrd to bail out on platforms that do not support
new key/attribute. 
Fix is to ignore new key/attribute if not present/supported yet.
Fix takes changes done as part of PR#https://github.com/Azure/sonic-platform-daemons/pull/76 which can be closed
once this gets merged
Verified manually xcvrd running fine after above changes.
also command  show interface transceiver is showing correct o/p

[xcvrd] Fix bailing out on platforms that do not support QSFP-DD

---

sonic-thermalctld/tests/test_thermalctld.py

Fix thermalctld tests which were broken by the transition to sonic-py-common. Logger class is now a superclass of the daemon itself.

Fix thermalctld tests which were broken by the transition to sonic-py-common

---

sonic-thermalctld/scripts/thermalctld
sonic-xcvrd/scripts/xcvrd

Previous commit to transition to importing sonic-py-common accidentally replaced all `logger` instances in xcvrd with `self`, although not all of these instances resided in the `DaemonXcvrd` class, breaking them. Here we add a global Logger instance for these references to use. Eventually we should refactor so that there is only one Logger instance created by xcvrd, not two.
- Also rename class names using PascalCase for consistency across the codebase.
- Also add Logger instance to ThermalMonitor class in thermalctld

[xcvrd][thermalctld] Add logger instances for helper functions and classes

---

sonic-ledd/scripts/ledd
sonic-pcied/scripts/pcied
sonic-psud/scripts/psud
sonic-syseepromd/scripts/syseepromd
sonic-xcvrd/scripts/xcvrd

As part of the migration from Python 2 to Python 3, this PR ensures that all Python files in sonic-platform-daemons are Python 3-compliant, and work with both Python 2 and Python 3.
Once this is merged, we can begin building Python 3-based versions of the sonic-platform-daemons packages.

Python 3 compliance

---

sonic-pcied/scripts/pcied

Please review @sujinmkang  @akokhan 
Path to 'pcie.yaml' must be '/usr/share/sonic/device/platform/', because pcied daemons run into pmon docker ("/usr/share/sonic/device/ \< platform>/<hardware_skus>" bind to "/usr/share/sonic/platform")
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>

[pcied] Fix path to pcie.yaml in pcied daemon

---

sonic-ledd/scripts/ledd
sonic-psud/scripts/psud
sonic-syseepromd/scripts/syseepromd
sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py
sonic-xcvrd/scripts/xcvrd

As part of consolidating all common Python-based functionality into the new sonic-py-common package, this pull request migrates from importing the sonic-daemon-base package to importing the sonic-py-common package. This is the next step toward resolving https://github.com/Azure/sonic-buildimage/issues/4999.
- Also reorganize imports for consistency

[201911] Migrate from sonic-daemon-base package to sonic-py-common package

---

sonic-psud/scripts/psud

psud update PSU data every 3 seconds while thermalctld update fan data every 60 seconds. So if we remove a PSU, psud detects it fast and "show platform psustatus" will show PSU status "Not OK", but thermalctld detects it later and "show platform fan" could still show PSU fan status "Present". The fix is trying to avoid the inconsistant.
psud will update PSU fan data to FAN_INFO table if any PSU is removed or inserted back.
Manual test.

[psud] Update FAN_INFO in psud to avoid inconsistant output of "show platform psustatus" and "show platform fan"

---

sonic-thermalctld/scripts/thermalctld

In regression, we found that thermal policy loop takes 8 to15 seconds sometimes which would enhance  the loop interval to 68 to 75 seconds. This change is to make the loop interval more accurate.
Record the elapse time for thermal policy, and start next iteration in (60 - elapse) seconds.
How I test this?
Manual test on Mellanox 2410.

[thermalctld] Optimize the thermal policy loop to make it execute every 60 seconds

---

sonic-ledd/scripts/ledd
sonic-xcvrd/scripts/xcvrd

The changes done here are for supporting ledd and xcvr for multi-asic platforms 
(i) In the ledd process, select now looks for events from the APP_DB in different namespaces.
(ii) In the xcvr process, the parent process and the sub processes connect to databases in all namespaces. The table in which namespace to be updated, is decided by the logical port ( we use the logical_port to asic_id mapping which is stored in the sfp_helper utility classes while parsing the port_config.ini files )
Related PR's
https://github.com/Azure/sonic-swss-common/pull/364
https://github.com/Azure/sonic-buildimage/pull/4932
https://github.com/Azure/sonic-platform-common/pull/100
Update with test results in Single ASIC and Multi-ASIC 
-------------------------------------------------------------
**SINGLE …

Platform daemon changes for multi asic platform

---

sonic-ledd/scripts/ledd

Update to ledd daemon based on sonic-swss-common updates to get the namespace ( sonic-swss-common PR #378 )

[ledd][multi-ASIC] Update to ledd based on sonic-swss-common updates

---

sonic-xcvrd/scripts/xcvrd

Why I did:-
Fix the xcvrd throwing error on sfprecover function on getKeys() not valid.
Need to update funciton based on per-asic changes
Signed-off-by: Abhishek Dosi <abdosi@microsoft.com>

Fix the xcvrd throwing error on sfprecover function

---

sonic-xcvrd/scripts/xcvrd

Eliminates unnecessary logs of the form:
```
xcvrd: Got event True {} in state 1
xcvrd: mapping from True {'-1': 'system_become_ready'} to system_become_ready
xcvrd: Got system_become_ready in normal state, ignored
```
What I did:
Don't need to do anything when the port_dict of transceiver_change is empty
How to verify:
Run on DUT to make sure xcvrd can detect tranceiver eeprom correctly and
there is no unmeaning logs anymore.
Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>

[xcvrd] Don't log unnecessary messages upon empty transceiver change event

---

sonic-pcied/scripts/pcied

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
Fix pcied daemon error:
```
Traceback (most recent call last):
File "/usr/local/bin/pcied", line 144, in <module>
main()
File "/usr/local/bin/pcied", line 141, in main
pcied.run()
File "/usr/local/bin/pcied", line 125, in run
self.check_pcie_devices()
File "/usr/local/bin/pcied", line 79, in check_pcie_devices
if err:
UnboundLocalError: local variable 'err' referenced before assignment
```

Fix pcied daemon failure

---

sonic-thermalctld/scripts/thermalctld

Fan status displays OK when a fan is removed from system, the expect value should be "N/A"
How I did?
If fan is not present, keep fan status value as "N/A".

[thermalctld] Fix issue: fan status should not be True when fan is absent

---

sonic-pcied/scripts/pcied

Signed-off-by: Petro Bratash <petrox.bratash@intel.com>
**- Why I did it**
pci-check.service and pcied daemon set different variables in STATE_DB.
- **_pci-check.service_** set "PCIE_STATUS|PCIE_DEVICES" variable with type string,
- **_pcied daemon_**  set "PCIE_STATUS|" -> "PCIE_DEVICES" variable with type hash.
Change name for variable with PCI devices status.
"PCIE_STATUS|" : "PCIE_DEVICES" --------------> "PCIE_DEVICES" : "status")
Related PR: https://github.com/Azure/sonic-buildimage/pull/5368
Fix the bug: https://github.com/Azure/sonic-buildimage/issues/5349

[pcied] Change STATE_DB key (PCIE_STATUS|PCIE_DEVICES -> PCIE_DEVICES)

---

sonic-thermalctld/scripts/thermalctld

**- Why I did it**
Part of thermalctld function is to handle user space thermal policies for events like fan/PSU removing, it works together with kernel thermal algorithm to make sure the switch won't be overheat.
Recently, we found that commit https://github.com/Azure/sonic-buildimage/commit/cbc75fe4c85fd01aded0bacb283c8bbf62adf2f8 changes its autorestart configuration in supervisord, and it won't be auto restarted after being killed. This PR is to make sure that thermalctld will be always restarted when it is killed.
1. Catch signal and assign it to a exit_code member data
2. Add a line "exit(self.exit_code)" to make sure it won't always exit with code 0
Manual test
**- Which release branch to backport (provide reason below if selected)** …

[thermalctld] Fix issue: thermalctld should be auto restarted when being killed

---

sonic-ledd/setup.py
sonic-pcied/setup.py
sonic-psud/setup.py
sonic-syseepromd/setup.py
sonic-thermalctld/setup.py
sonic-xcvrd/setup.py

Add 'wheel' to the list of packages required for building the package. This way it will be implicitly installed at build time, preventing the need to install the 'wheel' package explicitly in our build environment.

Add 'wheel' package to 'setup_requires' list in all setup.py files

---

sonic-thermalctld/scripts/thermalctld

Previous PR https://github.com/Azure/sonic-platform-daemons/pull/92 has been merged to 201911. The previous fix used a method FanStatus.is_ok, however, the implementation of this method is different between master and 201911. So we need an extra enhance for this issue.
fan status should be true only if FanStatus.is_ok() and fan_status is true.
By manual test and regression test.

[thermalctld] Fix fan status issue in 201911 

---

sonic-thermalctld/scripts/thermalctld

The existing code print exception like:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(e))
```
And it would print empty string if the exception class doesn't implement __str__. And the empty string is useless for debugging.
How to fix it?
Always print the exception using repr(e), like:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(repr(e)))
```

[thermalctld] Print exception using repr(e) to get more information

---

sonic-xcvrd/scripts/xcvrd
sonic-xcvrd/setup.py

Remove dependence on the 'enum' package, as we are currently transitioning from Python 2 to Python 3 and there are installation conflict issues between the `enum` package and the `enum34` package.
Add 'sonic-py-common' as dependencies in setup.py for xcvrd.
Also add spaces around "equals" signs.

[xcvrd] Remove dependence on enum; Add 'sonic-py-common' as dependencies in setup.py

---

sonic-xcvrd/scripts/xcvrd

Add check to make sure that the initializeGlobalConfig is invoked only in multi-asic platforms.
Additionaly remove the initializeGlobalConfig() call in the DomUpdate thread and SFPUpdate process. This is because initializeGlobalConfig() is already invoked and initialized in the parent Xcvrd daemon which is available to the child thread/process.
This fixes https://github.com/Azure/sonic-buildimage/issues/5680

[xcvrd] Remove log errors in single ASIC platforms with init Global config

---

sonic-thermalctld/scripts/thermalctld

Merge https://github.com/Azure/sonic-platform-daemons/pull/103 to 201911.
The existing code print exception like:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(e))
```
And it would print empty string if the exception class doesn't implement __str__. And the empty string is useless for debugging.
How to fix it?
Always print the exception using repr(e), like:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(repr(e)))
```

[thermalctld] Print exception using repr(e) to get more information for 201911

---

sonic-xcvrd/scripts/xcvrd
sonic-xcvrd/setup.py

Add dependence on 'enum' package back to xcvrd (basically reverting most of https://github.com/Azure/sonic-platform-daemons/pull/106). However, in setup.py, we only install the enum34 package if the version of Python we are installing for is < 3.4. Thus, when installing the Python 3 xcvrd package in Python 2.7, the Python 2 version of enum34 will be installed. However, if installing the Python 3 xcvrd package on Python 3.7, enum34 will not be installed, causing xcrvd to import the 'enum' module from the standard library. This should prevent any conflicts which arise when 'enum34' is ever installed on Python versions >= 3.4 by preventing this situation.

[xcvrd] Add enum dependence back; Install 'enum34' conditionally based on Python version

---

.gitignore
sonic-chassisd/pytest.ini
sonic-chassisd/scripts/chassisd
sonic-chassisd/setup.cfg
sonic-chassisd/setup.py
sonic-chassisd/tests/mock_module_base.py
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py

Introducing chassisd to monitor status of cards on a modular chassis
HLD: https://github.com/Azure/SONiC/pull/646
**-What I did**
Introducing a new process to monitor status of control, line and fabric cards.
**-How I did it**
Support of monitoring of line-cards and fabric-cards. This runs in the main thread periodically.
It updates the STATE_DB with the status information. 'show platform chassis-modules' will read from the STATE_DB
Support of handling configuration of moving the cards toadministratively up/down state. The handling happens as part
of a separate thread that waits on select() for config event from a CHASSIS_MODULE table in CONFIG_DB. 
**-How I verified it**

Introduce chassisd to monitor status of cards on chassis

---

.gitignore
sonic-psud/pytest.ini
sonic-psud/scripts/psud
sonic-psud/setup.cfg
sonic-psud/setup.py
sonic-psud/tests/mock_device_base.py
sonic-psud/tests/mock_platform.py
sonic-psud/tests/mock_swsscommon.py
sonic-psud/tests/test_psud.py

PSUd changes to computer power-budget for Modular chassis
HLD: Azure/SONiC#646
PSUd will introduce power requirements calculations. Platform APIs are introduced to provide consumers and total consumed power. Number of PSUs will help provide total supplied power
**Output of STATE-DB:**
```
"CHASSIS_INFO|chassis_power_budget 1": {
"expireat": 1603182970.639244,
"ttl": -0.001,
"type": "hash",
"value": {
"SUPERVISOR consumed_power": "80.0",
"FABRIC-CARD consumed_power": "185.0",
"FAN consumed_power": "999",
"LINE-CARD consumed_power": "1000.0",
"PSU supplied_power": "9000.0"
}
},
```

PSUd changes to compute power-budget for Modular chassis

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/mock_swsscommon.py
sonic-thermalctld/tests/test_thermalctld.py

Enhance thermalctld to write to chassis state-DB on a modular chassis
HLD: Azure/SONiC#646
In a modular chassis, the thermal information from all line-cards
will be updated to the chassis state-DB in the control-card.
Additionally, minimum and maximum temperatures will be recorded.
The fan control algorithm used by certain vendors will require
this information.

[Thermalctld] Update thermal info to CHASSIS_STATE_DB

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py
sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

Previously, chassisd and thermalctld assumed that the swsscommon library would not be installed in the unit testing environment. This is not a valid assumption, and would cause unit tests to fail if swsscommon was available in the unit test environement, because it would get imported, but there would be no Redis DB to communicate with.
This PR uses environment variables, which are set by the unit tests themselves, to determine whether to load the real or mock libraries. This solution is similar to what is done in sonic-utilities.

[chassisd][thermalctld] Import of mock libraries determined by environment variable

---

sonic-chassisd/scripts/chassisd
sonic-thermalctld/scripts/thermalctld

This was missed in https://github.com/Azure/sonic-platform-daemons/pull/112

[chassisd][thermalctld] Import os module, now needed for env var checking

---

sonic-chassisd/tests/test_chassisd.py
sonic-thermalctld/tests/test_thermalctld.py

Since these tests are run via unittest infrastructure, and not via Pytest, `setup_function()` is not the proper location to set these variables.

[chassisd][thermalctld] Set testing env var at top of file, not in setup_function()

---

sonic-psud/scripts/psud
sonic-psud/tests/test_psud.py

Previously, psud assumed that the swsscommon library would not be installed in the unit testing environment. This is not a valid assumption, and would cause unit tests to fail if swsscommon was available in the unit test environment, because it would get imported, but there would be no Redis DB to communicate with.
This PR uses environment variables, which are set by the unit tests themselves, to determine whether to load the real or mock libraries. This solution is similar to what is done in sonic-utilities.

[psud] Import of mock libraries determined by environment variable

---

sonic-chassisd/scripts/chassisd
sonic-psud/scripts/psud
sonic-thermalctld/scripts/thermalctld

When  `PSUD_UNIT_TESTING` and  `THERMALCTLD_UNIT_TESTING` variables don`t set we have the next problems:
```
psud Traceback (most recent call last):
psud File "/usr/local/bin/psud", line 21, in <module>
psud if os.environ["PSUD_UNIT_TESTING"] == "1":
psud File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
psud raise KeyError(key)
psud KeyError: 'PSUD_UNIT_TESTING'
```
```
thermalctld Traceback (most recent call last):
thermalctld File "/usr/local/bin/thermalctld", line 19, in <module>
thermalctld if os.environ["THERMALCTLD_UNIT_TESTING"] == "1":
thermalctld File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
thermalctld raise KeyError(key)
thermalctld KeyError: 'THERMALCTLD_UNIT_TESTING'
```
Also fixed the same issue in `chassisd`.
Signed-off-by: Petro Bratash …

[thermalctld] [psud] [chassisd] Fix crash with undefined environment variable

---

sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

On this [PR ](https://github.com/Azure/sonic-platform-daemons/commit/ef15ff51dfc70791d0b31d097e56e70ef6c25441)was changed [name generation:
](https://github.com/Azure/sonic-platform-daemons/blob/f63ec30521d690e9bbef76fdbbed52e4af56ec44/sonic-thermalctld/scripts/thermalctld#L591)
and after this changes **_test_updater_thermal_check_min_max()_**  fails:
```
01:33:00  ______________________ test_updater_thermal_check_min_max ______________________
01:33:00  
01:33:00      def test_updater_thermal_check_min_max():
01:33:00          chassis = MockChassis()
01:33:00      
01:33:00          thermal = MockThermal()
01:33:00          chassis.get_all_thermals().append(thermal)
01:33:00      
01:33:00          chassis.set_modular_chassis(True)
01:33:00          chassis.set_my_slot(1)
01:33:00 …
```

Fix test_updater_thermal_check_min_max() failure

---

sonic-psud/scripts/psud

Without this change, leds were only set when an event happened.
Given that power supplies are assumed present by default, leds would never be set to `green`.
Instead they would have been left in the state the platform initialization left them (e.g `off`)
Fix for #124

[psud] Make sure psu leds are set on the first run

---

sonic-thermalctld/scripts/thermalctld

There could be 2 fans in the same drawer and the final fan drawer LED state is determined by all fans status in this drawer. So we have to update fan LED status after updating other fan status.
Similar fix is already in master.
Use a separate loop to update the fan led in database after updating all other fan status.
Run test cases in test_platform_info.py.

[thermalctld][201911] Set led status after updating all other fan status

---

sonic-ledd/scripts/ledd
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

The check for multiAsic before calling initializeGlobalConfig was done in xcvrd earlier. 
Adding now to the other processes in sonic-platform-daemons as well.

Clean some unused variables, check for multiAsic before calling initializeGlobalConfig

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Summary:
This PR provides the support for replacing the state DB updates from 'failure' to 'unknown' in case there is an error event in the functioning of Y cable. 
added the changes in xcvrd/xcvrd_utilities/y_cable_helper.py. Replaced and added the state update at scenario's where there could be error
the schema agreed upon with linkmgr and orchagent interaction with xcvrd, is that if there is an error event xcvrd need to fill the state DB with 'unknown' as the state value rather than 'failure', this PR handles that
identified error scenario's in the code and made the changes 
Ran the pmon docker with the changed file, and redis-cli to obtain the events and check the functionality is working

[xcvrd] Fix y_cable state updates from 'failure' to 'unknown' on error conditions/events

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Summary:
This PR provides replaces the logic to check mux_direction on the y_cable by checking the mux_direction register instead of actively linked and routing TOR register
added the changes in y_cable_helper.py by replacing the API
check_mux_direction is required as per design to replace the active_linked_tor_side
active_linked_tor_side -> check_mux_direction 
check_mux_direction will be utlized as for establishing mux direction explicitly
changed the api calls at appropriate places
Ran the pmon docker with the changed file, and redis-cli to obtain the events and check the functionality is working, also confirmed the same with i2c commands by toggling the mux

[xcvrd] replace check_active_linked_tor_side api to check_mux_direction for establishing the direction mux points to on y_cable

---

sonic-psud/setup.py
sonic-syseepromd/setup.py
sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/setup.py
sonic-xcvrd/setup.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

python2 is end of life and SONiC is going to support python3. This PR is to change code in xcvrd, psud, thermalctld and syseeprom to make it compatible with both python3 and python2.
Use tool 2to3 to transfer code
1. Manual test to make sure all daemons are up and no error logs in syslog
2. Run platform regression test on a few platforms

Support python3 for xcvrd, psud, thermalctld and syseepromd

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/setup.py
sonic-chassisd/tests/mock_module_base.py
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py
sonic-ledd/scripts/ledd
sonic-ledd/setup.py
sonic-pcied/scripts/pcied
sonic-pcied/setup.py
sonic-psud/scripts/psud
sonic-psud/setup.py
sonic-psud/tests/mock_device_base.py
sonic-psud/tests/mock_platform.py
sonic-psud/tests/mock_swsscommon.py
sonic-psud/tests/test_psud.py
sonic-syseepromd/scripts/syseepromd
sonic-syseepromd/setup.py
sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/setup.py
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/mock_swsscommon.py
sonic-thermalctld/tests/test_thermalctld.py
sonic-xcvrd/setup.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Align style with slightly modified PEP8 standards (extend maximum line length to 120 chars). This will also help in the transition to Python 3, where it is more strict about whitespace.
Done using `autopep8 --in-place --max-line-length 120` and some manual tweaks.

Align style with PEP8 standards

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Summary:
This PR provides removes the delete logic on command probe message received from linkmgr after processing the message
added the changes in y_cable_helper.py by replacing the API
the delete message tends to create an error scenario if many probe messages come and redis-api fails to retrieve the message contents  
removed the call for deletion of the message 
Ran the pmon docker with the changed file, and redis-cli to obtain the events and check the functionality is working

[xcvrd] removing the delete notification message logic for command probe in mux cable driver

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py

Enhance chassisd to monitor midplane status of the cards in modular chassis
HLD: Azure/SONiC#646
-What I did
Add monitoring of the midplane or internal ethernet network between supervisor and line-card modules.
-How I did it
Along with status monitoring, also monitor the midplane reachability between supervisor and modules.
It updates the STATE_DB with the status information. 'show chassis-modules midplane-status' will read from the STATE_DB
-How I verified it
With UT and platform specific validation
**CLI output**
https://github.com/Azure/sonic-utilities/pull/1267
**UT output**
```
platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /sonic/src/sonic-platform-daemons/sonic-chassisd, inifile: pytest.ini
plugins: cov-2.6.0
collected 10 items …
```

[chassisd] Monitor midplane status

---

sonic-xcvrd/tests/test_xcvrd.py

xcvrd unit test failed when building it with python3: 
```
17:23:50  _____________________ ERROR collecting tests/test_xcvrd.py _____________________
17:23:50  tests/test_xcvrd.py:36: in <module>
17:23:50      class TestXcvrdScript(object):
17:23:50  tests/test_xcvrd.py:41: in TestXcvrdScript
17:23:50      @patch('xcvrd.xcvrd.logical_port_name_to_physical_port_list', MagicMock(return_value=[0]))
17:23:50  E   NameError: name 'patch' is not defined
```
import the package patch
How I test this?
Run build

[xcvrd] Fix unit test issue with Python 3

---

sonic-psud/scripts/psud

**Issue:**
- The PSU FAN information is not updated in the redis-db.
**Steps to reproduce:**
- Load latest master image and check redis-db PSU Fan table.
**To fix this issue:**
- Initialize self.presence and other variables in PsuStatus dunder init to False instead of True.
- Import datetime module.
- Discussions related to this issue can be seen in https://github.com/Azure/sonic-platform-daemons/issues/136
UT:
[psu daemon fix UT.txt](https://github.com/Azure/sonic-platform-daemons/files/5746605/psu.daemon.fix.UT.txt)

[psud] Fix issue where PSU Fan info is not updated in State DB

---

sonic-psud/setup.py
sonic-psud/tests/mock_platform.py
sonic-psud/tests/test_PsuStatus.py
sonic-psud/tests/test_psud.py

- Add 100% unit test coverage of `PsuStatus` class in psud.
- Add skeleton of class to test `DaemonPsud` class
- Add test case for `get_psu_key()` and `try_get()` helper functions
- Add checks to import 'mock' from the 'unittest' package if running with Python 3
Overall psud unit test coverage increases from 39% to 51%.
Previous unit test coverage:
```
Name           Stmts   Miss  Cover
----------------------------------
scripts/psud     381    233    39%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```
Unit test coverage with this patch:
```
Name           Stmts   Miss  Cover
---------------------------------- …
```

[psud] Increase unit test coverage

---

sonic-thermalctld/pytest.ini
sonic-thermalctld/setup.py
sonic-thermalctld/tests/test_thermalctld.py

Report Pytest unit test coverage for thermalctld.
Current coverage:
```
Name                  Stmts   Miss  Cover
-----------------------------------------
scripts/thermalctld     424    113    73%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```
- Also add check to import 'mock' from the 'unittest' package if running with Python 3

[thermalctld] Report unit test coverage

---

sonic-ledd/pytest.ini
sonic-ledd/scripts/ledd
sonic-ledd/setup.cfg
sonic-ledd/setup.py
sonic-ledd/tests/mock_swsscommon.py
sonic-ledd/tests/test_ledd.py

- Refactor ledd:
- Remove useless try/catch from around imports
- Move argument parsing out of `DaemonLedd.run()` method and into `main()` function, a more appropriate location
- Fix LGTM alert for unreachable code
- Add unit tests and report coverage:
- Test passing good and bad command-line arguments to ledd process
Unit test coverage with this patch:
```
Name           Stmts   Miss  Cover
----------------------------------
scripts/ledd      66     34    48%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```

[ledd] Minor refactor; add unit tests

---

sonic-pcied/scripts/pcied

In pcied, added support to collect AER stats belonging to different severities for AER supported PCIe devices and update it in STATE_DB.
The key used to represent a PCIE device for storing its AER stats in STATE_DB is of the format `PCIE_DEVICE|<Bus>:<Dev>.<Fn>`.
For every device, AER stats will be stored as key, value pairs where key is of the format `<severity>|<AER Error type>` and the device ID will be stored with key `id`.
HLD: Azure/SONiC#678, Azure/SONiC#720
Depends on: Azure/sonic-platform-common#144

[pcied] Add PCIe AER stats collection

---

sonic-ledd/scripts/ledd
sonic-ledd/tests/test_ledd.py

- Refactor ledd to allow for more thorough unit testing
- Remove infinite loop from `run()` method to allow unit testing of the method. Instead, call the `run()` method in an infinite loop in `main()`
- Increase overall ledd unit test coverage from 48% to 93%.
Previous unit test coverage:
```
Name           Stmts   Miss  Cover
----------------------------------
scripts/ledd      66     34    48%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```
Unit test coverage with this patch:
```
Name           Stmts   Miss  Cover
----------------------------------
scripts/ledd      72      5    93%
Coverage HTML written to dir …
```

[ledd] Refactor to allow for more thorough unit testing; Increase unit test coverage

---

sonic-pcied/scripts/pcied

[pcied] Remove unnecessary message and move the configuration path from plugin directory to platform directory
This PR fixes https://github.com/Azure/sonic-buildimage/issues/5819 and fixes https://github.com/Azure/sonic-buildimage/issues/6437.
- Remove unnecessary repeated message
- Move the configuration path from plugin directory to platform directory

[pcied] Remove unnecessary message and move the configuration path

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Summary:
This PR provides the necessary infrastructure to initialize the mux_cable info and static tables and post them within state db
as part of xcvrd. The data is posted every 60 secs and streaming telemetry can utilize this info. 
Added changes in the sonic_xcvrd directory of sonic-platform-daemons
To add the necessary infrastructure for Credo Y cable support for posting streaming telemetry data inside state-db
Added the necessary changes and a new xcvrd_utilities sub directory for utilities of y_cable code.
Ran the docker restart command for pmon to ascertain the values are getting posted inside the state-db.
Ran redis-cli commands to confirm all the data exists as intended
Platform must have optoe driver support for  instantiation of sysfs/eeprom 
The following are snapshots on …

[xcvrd] Store mux_cable telemetry data in State DB

---

sonic-xcvrd/xcvrd/xcvrd.py

Make functions used for media setting python3 compatible
fixes #139 
Verified that the media settings are updated in APPL_DB by xcvrd in dynamic transceiver tuning supported platform. 
Logs: [UT_logs.txt](https://github.com/Azure/sonic-platform-daemons/files/5987046/UT_logs.txt)

[xcvrd] Make functions used for media setting python3 compatible

---

sonic-xcvrd/xcvrd/xcvrd.py

Implement a better check for logical_port_name_to_physical_port_list function.
Currently it will only accept names that start with "Ethernet". If we try to add other ports it will crash.
In the future Arista will implement other port types. For example "Recirc0".

[xcvrd] Fix xcvrd crash on other port prefixes

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

- What I did
Save the dom_capability gotten from transceiver into db
- How I did it
Add a field-value pair when it try to set the table inside "post_port_sfp_info_to_db" function
- How to verify it
Compare one transceiver which support diagnostic monitoring function to another transceiver which doesn't support it.
Check the db data of the transceiver
Run 'show interfaces transceiver eeprom' command.

[xcvrd] Save the dom_capability of transceiver into db

---

sonic-xcvrd/scripts/xcvrd

[xcvrd] Change in xcvrd ports cache creation, now ports are being fetched from config DB.
This change is not needed in master since in master the whole code was rewritten as part of the DPB therefore the bug was solved there (same goes for 202012).
Signed-off-by: liora <liora@nvidia.com>
**- Dependencies**
This must be merged only after https://github.com/Azure/sonic-platform-common/pull/172 is merged
**- Why I did it**
Fix community issue https://github.com/Azure/sonic-platform-daemons/issues/110
Issue description: newly created ports as part of dynamic port breakout process are not being added to XCVRD cache, hence not shown in SNMP get on entPhysicalEntry mib.
Add new option in XCVRD ports cache creation, fetch ports from config DB instead of port_config.ini
**- How …

[201911][xcvrd] Change in xcvrd ports cache creation, now ports are being fetched from config DB

---

sonic-xcvrd/xcvrd/xcvrd.py

- xcvrd crashes in media settings supported platforms due to py3 compatibility issue in xcvrd media settings .
```
Mar  2 04:50:36.960634 sonic INFO pmon#/supervisord: xcvrd Traceback (most recent call last):
Mar  2 04:50:36.960704 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 8, in <module>
Mar  2 04:50:36.960744 sonic INFO pmon#/supervisord: xcvrd     sys.exit(main())
Mar  2 04:50:36.960785 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1381, in main
Mar  2 04:50:36.960823 sonic INFO pmon#/supervisord: xcvrd     xcvrd.run()
Mar  2 04:50:36.960862 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1329, in run
Mar  2 04:50:36.960900 sonic INFO …
```

[xcvrd] Fix crash on platforms which support media settings with Python 3

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This change essentially omits a look inside the state DB for HW_MUX_CABLE_TABLE and just directly goes to the muxcable
eeprom to either toggle or remain Iin the same state as is requested from the incoming message from orchagent, and then write back to the DB
This fix will help in debugging the initialization loop since now other modules will not be dependent on stale state present in
HW_MUX_CABLE_TABLE. 
Tested on starlab testbed with integration of other modules. 
Change works well

fix the muxcable state change notification received from other modules, omit the check inside hw_state table

---

sonic-xcvrd/xcvrd/xcvrd.py

If 'dom_capability' not in port_info_dict, insert 'N/A'
Currently, some vendors are using custom transceiver info parsers which do not yet provide the `dom_capability` field in the results of `get_transceiver_info()`. However, PR https://github.com/Azure/sonic-platform-daemons/pull/72 introduced storing this value to State DB under the assumption that it would always be present. On platforms where this value is not present, it would cause xcvrd to crash (see issue: https://github.com/Azure/sonic-buildimage/issues/6978).
This change will prevent a crash if it is not present, and will in turn save `'N/A'` as the `dom_capability` value in State DB.
Tested on one affected platform.

[xcvrd] Fix crash: If 'dom_capability' not in port_info_dict, insert 'N/A'

---

sonic-xcvrd/scripts/xcvrd

This reverts commit 61acd3a2e4a457f3bc706cbfaf3162b947763864  which introdunce by PR https://github.com/Azure/sonic-platform-daemons/pull/155
the above commit change the way of xcvrd reading info from port_config.ini to fetch from DB by extending read_porttab_mappings in sfputilhelper. However there is still some issue in the new change which could cause xvrd crash due to get a wrong port number. 
We believe read from DB is the correct way to go, however, before we fix the bug we need to revert this change temporarily.
```
Mar  3 13:10:24.156122 l-csi-4700-05 INFO pmon#supervisord: xcvrd SFP index 71 out of range (0-31)
Mar  3 13:10:24.156343 l-csi-4700-05 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Mar  3 13:10:24.156343 l-csi-4700-05 INFO pmon#supervisord: xcvrd …
```

Revert "[xcvrd] Change in xcvrd ports cache creation, now ports are being fetched from config DB"

---

sonic-syseepromd/scripts/syseepromd

[syseepromd] Update warning message in syseepromd to be more informative
Signed-off-by: liora <liora@nvidia.com>
Daemon syseepromd is loading data from eeprom.
When syseepromd fails to load data from eeprom using the new platform API, it tries again using the old plugins way.
In the case where the first method failed, warning message was not informative and confusing, I fixed it.
Update warning message to be more informative.
I ran syseepromd manually and verifed that warning is printed as expected.

[syseepromd] Update warning message to be more informative

---

azure-pipelines.yml
sonic-thermalctld/pytest.ini
sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/setup.py
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/mock_swsscommon.py
sonic-thermalctld/tests/mocked_libs/sonic_platform/__init__.py
sonic-thermalctld/tests/mocked_libs/sonic_platform/chassis.py
sonic-thermalctld/tests/mocked_libs/sonic_platform/platform.py
sonic-thermalctld/tests/mocked_libs/swsscommon/__init__.py
sonic-thermalctld/tests/mocked_libs/swsscommon/swsscommon.py
sonic-thermalctld/tests/test_thermalctld.py

- Refactor thermalctld to reduce the amount of code in infinite loops, thus allowing us better unit test coverage
- Refactor mock_platform.py such that it inherits from sonic-platform-common in order to ensure it is aligned with the current API definitions (this introduces a test-time dependency on the sonic-platform-common package)
- Increase pytest verbosity to prevent truncation of error messages
- Miscellaneous cleanup:
- Fixes to grammar
- Remove unnecessary punctuation from log messages
- Increase overall unit test unit test coverage from 73% to 93%
Previous unit test coverage:
```
Name                  Stmts   Miss  Cover
-----------------------------------------
scripts/thermalctld     424    113    73%
``` …

[thermalctld] Refactor to allow for greater unit test coverage; Add more unit tests

---

sonic-psud/scripts/psud
sonic-psud/tests/test_PsuStatus.py

Bug fix: the fields that are not supported by the vendor should be "N/A" in STATE_DB
- Initialize fields as "N/A" and set the field to "N/A" for those not supported by vendor API
- Update set_voltage, set_temperature, treating "N/A" instead of None as invalid values
- Update unit test cases accordingly
Signed-off-by: Stephen Sun <stephens@nvidia.com>
Manually test and regression test

[psud] Bug fix: the fields that are not supported by vendor should be "N/A" in STATE_DB

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Gracefully handle improper 'specification_compliance' field; also fix other potential bugs and adjust some style
The 'specification_compliance' field of transceiver info is expected to be a string representation of a dictionary. However, there is a chance, upon some kind of platform issue that a vendor's platform API returns something like 'N/A'. In this case, xcrvd would crash. Rather than crash, xcvrd should handle this gracefully and log a warning message instead.
Also fixed a couple potential bugs where `default_dict` was being compared to `0`, when it should have been `len(default_dict)`
Also rename some constants using uppercase naming convention.
Tested on one platform; also added a unit test

[xcvrd] Gracefully handle improper 'specification_compliance' field; also fix other potential bugs

---

sonic-thermalctld/scripts/thermalctld

Changed the chassis definition to be a part of the class do the chassis will be found in run() function
Without the change, an error appears in syslog. 
```  ERR pmon#thermalctld: Caught exception while running thermal policy - NameError("name 'chassis' is not defined") ```
N/A

[thermalctld] Fix 'NameError("name 'chassis' is not defined")' error in log

---

sonic-syseepromd/pytest.ini
sonic-syseepromd/scripts/syseepromd
sonic-syseepromd/setup.cfg
sonic-syseepromd/setup.py
sonic-syseepromd/tests/mock_swsscommon.py
sonic-syseepromd/tests/mocked_libs/sonic_platform/__init__.py
sonic-syseepromd/tests/mocked_libs/sonic_platform/chassis.py
sonic-syseepromd/tests/mocked_libs/sonic_platform/platform.py
sonic-syseepromd/tests/mocked_libs/swsscommon/__init__.py
sonic-syseepromd/tests/mocked_libs/swsscommon/swsscommon.py
sonic-syseepromd/tests/test_syseepromd.py

- Refactor syseepromd to eliminate infinite loops to allow for increased unit test coverage
- Refactor signal handler and ensure daemon always exits with non-zero exit code so that supervisor will restart it
- Add unit tests
Unit test coverage increases from 0% to 90%:
```
Name                 Stmts   Miss  Cover
----------------------------------------
scripts/syseepromd      97     10    90%
```
To increase unit test coverage >= 90% in order to prevent regressions
The refactored psud has been tested on a physical DUT and the unit test results can be examined via the Azure Pipelines check builds in this PR.

[syseepromd] Add unit tests; Refactor to allow for greater unit test coverage

---

sonic-thermalctld/scripts/thermalctld

Currently, when thermalctld loading an invalid policy file, it catches the exception and call sys.exit. However, there is a sub process created and sys.exit cause the daemon hang forever. Actually, it is not necessary to exit thermalctld here because:
1. Other than running thermal policy, there is a sub process which monitoring thermal status. So even if there is an invalid policy file, thermal monitoring can still work.
2. Even if we exit here, supervisord will restart thermalctld and it fall into the same exception again and again. 
The issue failed a few test cases in test_platform_info.py
test_platform_info.py

[thermalctld] No need exit thermalcltd when loading invalid policy file

---

sonic-ledd/scripts/ledd

Inband port is avaialable in PORT table. But regular port handlings are
not applicable for Inband port. Changes in this PR are to avoid regular
port handling on Inband port.
This PR depends on sonic-buildimage PR https://github.com/Azure/sonic-buildimage/pull/6477

[voq/inbandif] Voq inbandif port

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

Selectable object can return multiple fields, however current code
process only the first filed and wait till the next selectable
is triggered. This PR consumes all fields that were returned by
a selectable object. This results in reducing processing time from
order of second to order of millisecond.
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

[muxcable] Fix Redis Selectable Processing

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

1. Currently in sonic, for 400G pre-emphasis settings is not programmed via common methodology. 
We use Vendor Name + PN to program which would consume memory and never ending process as we need to add Vendor name + PN for every optic.
2.  For 100G/40G optics, specification compliance is not displayed. Only for DAC, the specification compliance was displayed.
1. With this PR, we can program the pre-emphasis settings for both DAC,AOC and optics.
QSFP_DD parser doesn't have specification compliance which was need to program pre-emphasis settings.
The platform API code can be changed to return the type_of_media_interface for 400G media specification compliance, so that the type of media can be determined.
https://github.com/Azure/sonic-platform-common/blob/a95834b65a9f3b17ab1ce4e1ba5d1a60102e …

[xcvrd] Enhance Media Settings

---

sonic-xcvrd/scripts/xcvrd

Gracefully handle improper 'specification_compliance' field; also fix other potential bugs and adjust some style
The 'specification_compliance' field of transceiver info is expected to be a string representation of a dictionary. However, there is a chance, upon some kind of platform issue that a vendor's platform API returns something like 'N/A'. In this case, xcrvd would crash. Rather than crash, xcvrd should handle this gracefully and log a warning message instead.
Also fixed a couple potential bugs where `default_dict` was being compared to `0`, when it should have been `len(default_dict)`
Also rename some constants using uppercase naming convention.
This is a backport of https://github.com/Azure/sonic-platform-daemons/pull/169 to the 201911 branch.

[201911] [xcvrd] Gracefully handle improper 'specification_compliance' field; also fix other potential bugs

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR changes the logic to use "mux_cable" table as identifier, and only those ports which have this table inside config DB and key pair of "state:auto/active" will be processed as having a Y-Cable port.
The earlier logic was using the PORT table tag with a mux_cable:true key-value pair. 
change the logic to initiate Y-Cable logic
Required for changing the logic, so that this can be integrated with images which don't support "mux_cable" tag inside config DB
Ran the change on Arista 7050cx3 platform by restarting the container

[xcvrd] Change the y_cable presence logic to use "mux_cable" table as identifier from Config DB

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

Make thermalctld exit as soon as possible. Depends on https://github.com/Azure/sonic-platform-common/pull/187
During config reload flow, supervisord sends SIGTERM to thermalctld. However, if thermalctld cannot exit in 10 seconds, supervisord sends SITKILL to thermalctld. In this case, sub process of thermalctld might still stay in memory as a zombe process. This PR is aimed to fix this.
1. thermalctld unit test to cover the changes
2. run platform related regression cases and all passed

[thermalctld] Enable stopping thermal manager

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

When using redis select, xcvrd is sleeping for 100msec which appears
unnecessary after process all content of selectable objects.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
Reduce overall time it takes to switch multiple/all ports
Test on test cluster where 24 ports were switched and saw 100msec to 200msec gain in switching time of all ports. Individual port switch time is still within 20msec~30msec.

[muxcable] Remove Xcvrd Sleep

---

sonic-psud/scripts/psud
sonic-psud/tests/mock_platform.py
sonic-psud/tests/test_DaemonPsud.py

Added "hardware revision" field to list of platform fields to sync to STATE_DB for the PSU. Also updated relevant unit tests. 
Now that hardware revision exists as a platform 2.0 field for all devices, it is appropriate to synchronize this field to STATE_DB for PSUs as is done with all other fields. This will allow this field to be exposed to CLI tools through psushow in the future which reads state from STATE_DB. 
This has been tested on all mellanox platforms aside from MSN2010. Tested by deploying change and verifying that "revision" was present in STATE_DB for all platforms that support it.

[psud] Add PSU Hardware Revision to Redis STATE_DB

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR adds support for logging events for change requests received by xcvrd from swss into state DB. 
a typical log would look like this:
` 1) "xcvrd_switch_standby_start"`
`2) "2021-05-13 10:01:15.690835"`
`3) "xcvrd_switch_standby_end"`
`4) "2021-05-13 10:01:15.696051"`
where the key-value pairs signify the type of event requested out of 
`active/standby/unknown` and the timestamp associated with the event. 
This is required for xcvrd to log the events which it receives in form of requests from swss or any other module into the DB. The timestamp will be useful for debugging the timeline of an event processing from a perspective of other modules as well as xcvrd itself. 
ran the changes on starlab testbed, by changing the file in …

[xcvrd] add support for logging mux_metrics events into state DB

---

sonic-chassisd/scripts/chassis_db_init
sonic-chassisd/setup.py
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/test_chassis_db_init.py

I added a new script `chassis_db_init` that uploads chassis hardware information such as serial number, model number and hardware revision to the STATE_DB under the CHASSIS_INFO table. 
I made this change in order to expose the chassis hardware information to SONiC user space and allow CLI utilities to access it in order to expose it to the user. 
Unit tests were added and was deployed and tested on Mellanox platform MSN2700.

[chassisd] Add script to initialize chassis info in STATE_DB

---

sonic-thermalctld/tests/mocked_libs/swsscommon/swsscommon.py
sonic-thermalctld/tests/test_thermalctld.py

Existing test will mix true swsscommon package with the mocked one in sonic_py_common
This is blocking https://github.com/Azure/sonic-buildimage/pull/7655
Unit test

Mocking path early so it will applied to sonic_py_common, mock more swsscommon classes

---

sonic-psud/tests/mocked_libs/swsscommon/swsscommon.py
sonic-psud/tests/test_DaemonPsud.py
sonic-psud/tests/test_psud.py
sonic-syseepromd/tests/mocked_libs/swsscommon/swsscommon.py
sonic-syseepromd/tests/test_syseepromd.py

Following https://github.com/Azure/sonic-platform-daemons/pull/187 to fix the same issue with other packages
This is blocking Azure/sonic-buildimage#7655
Unit test

Mock path early so it will applied to sonic_py_common, mock platform_chassis

---

sonic-thermalctld/scripts/thermalctld

Backport PR https://github.com/Azure/sonic-platform-daemons/pull/167 since there is no clean cherry-pick.
Initialize fan led in thermalcltd for the first run. Add a flag "led_initialized" in FanStatus and set it as False on __init__ function. FanUpdater will use this flag to determine if fan led should be set even if no fan event detected.
Make sure fan led is initialized to correct color.
Manual test

[201911] Initialize fan led in thermalctld for the first run

---

sonic-pcied/scripts/pcied

swsssdk will be deprecated, and the python version of redis accessing classes will be replace by the same name classes in swsscommon, which are SWIG wrapped C++ code.

Replace swsssdk.SonicV2Connector with swsscommon implementation

---

sonic-xcvrd/xcvrd/xcvrd.py

I added a `del` directive for the global `platform_chassis` object in `xcvrd` on deinit to ensure that the pointer is properly cleaned up such that the `__del__()` method is successfully called on the chassis object which closes its connection to SAI. 
On Mellanox platforms on 202012 we are seeing that in some cases xcvrd is maintaining the socket to the API past its deconstruction causing an error from SAI. This was traced by reproducing the issue and identifying that the pmon container was causing this issue where xcvrd is the only daemon within pmon that opens a SDK socket on Mellanox. 
Error in log...
```
syncd#SDK: [SX_API_INTERNAL.ERR] Failed command read at communication channel: Connection reset by peer
```
Change was uploaded to xcvrd on running pmon container on a switch running …

[xcvrd] Force cleanup of chassis global variable on deinit

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py

Signed-off-by: ngocdo <ngocdo@arista.com>
chassisd inside pmon queries asic information from platform modules and stores it into CHASSIS_STATE_DB of redis_chassis.
The reason we keep information in CHASSIS_STATE_DB because it's accessible by swss containers.
Asic information includes asic pci address, module name, and asic id in the module. For example, CHASSIS_STATE_DB will look like below:
```
127.0.0.1:6379[6]> HGETALL "CHASSIS_ASIC_TABLE|ASIC0"
1) "asic_pci_address"
2) "0000:09:00.0"
3) "module_name"
4) "FABRIC-CARD0"
5) "asic_id_in_module"
6) "0"
127.0.0.1:6379[6]> HGETALL "CHASSIS_ASIC_TABLE|ASIC1"
1) "asic_pci_address"
2) "0000:0b:00.0"
3) "module_name"
4) "FABRIC-CARD0"
5) "asic_id_in_module"
6) "1"
127.0.0.1:6379[6]> HGETALL "CHASSIS_ASIC_TABLE|ASIC2"
1) "asic_pci_address"
2) …
```

Collect asic info and store in CHASSIS_STATE_DB

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR adds support for logging required in debugging events for change/probe requests received by xcvrd from swss and linkmgr into state DB. 
a typical log would look like this:
`Jun 17 05:55:39.302379  NOTICE pmon#xcvrd[33]: Y_CABLE_DEBUG: trying to enable/disable debug logs`
`Jun 17 05:55:39.302379  NOTICE pmon#xcvrd[33]: Y_CABLE_DEBUG: received an event for port transition Ethernet4`
`Jun 17 05:55:39.302575  NOTICE pmon#xcvrd[33]: Y_CABLE_DEBUG: xcvrd trying to transition port Ethernet4 from standby to active`
`Jun 17 05:55:39.307872 NOTICE pmon#xcvrd[33]: Y_CABLE_DEBUG: Successful in toggling mux to ToR A for port 2`
where both probe events and change events are logged inside xcvrd.
This is required for xcvrd to log the events …

[xcvrd] add debug logs for y_cable change events/probes

---

sonic-pcied/scripts/pcied

Fix https://github.com/Azure/sonic-buildimage/issues/7993
- Fixes wrong log line when Pcie module does not exists that causes the pcied daemon to enter FATAL state.
- Change log level of line "Failed to load platform Pcie module" to notice since this is not an error flow, this is part of the normal loading flow we expect when a vendor didn't supply a Pcie class.
Load image, check pcied daemon status.

[pcied] Fix pcied failure to load due to 'pcied NameError: name 'self' is not defined'

---

sonic-xcvrd/xcvrd/xcvrd.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Added delay of 2 seconds for QSFP's MgmtInit after module presence is detected
As per CMIS spec : http://www.qsfp-dd.com/wp-content/uploads/2021/05/CMIS5p0.pdf (see D.1.3 Software Configuration and Initialization) module's resetL must be de-asserted and a delay of 2 seconds is required for MgmtInit to complete.
TBD
Verify the eeprom dump and link comes UP under following scenarios:
1. Multiple reboots with optics from different vendors across various ports
2. OIR same optics multiple times on same port
3. Swap optics from different vendors on same port
4. Repeat 2 and 3 across multiple ports

Introduce mgmtinit delay after transceiver reset

---

sonic-pcied/pytest.ini
sonic-pcied/scripts/pcied
sonic-pcied/setup.cfg
sonic-pcied/setup.py
sonic-pcied/tests/mock_platform.py
sonic-pcied/tests/mocked_libs/swsscommon/__init__.py
sonic-pcied/tests/mocked_libs/swsscommon/swsscommon.py
sonic-pcied/tests/test_DaemonPcied.py
sonic-pcied/tests/test_pcied.py

Description
Refactor the pcied and add the unit test
Motivation and Context
Added unit test to increase the pmon unit test coverage.
How Has This Been Tested?
Build with unit test enabled and run manually on a dut to verify the pcied.

[202012] Refactor Pcied and add unittest

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR fixes the logging for mux_metrics for writing anything to the state DB for a state transition. Basically previously xcvrd would first post the query result to the DB and only then update its own metric for state transition, but now we do the reverse.
Second change was motivated by the sequence of events which happen inside state transition for mux-metrics table. Previously orchagent reports finishing the transition before xcvrd which is not the case. Ideally xcvrd does the transition first followed by orchagent followed by linkmgr
Ran the change on Arista7050cx3 testbed.

[y-cable] fix for logging the xcvrd metrics before writing the state to the State-DB

---

sonic-thermalctld/scripts/thermalctld

Fix issue described in https://github.com/Azure/sonic-buildimage/issues/8230
Add safety check before calling api

[Fix issue #8230] Check thermal_manager is available before calling

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR integrates vendor specific class objects inside xcvrd for Y-Cable API's to be called. 
Detailed designed document can be found https://github.com/Azure/SONiC/pull/757
Basically xcvrd now has  an interface for Y-Cable to interact with PMON docker and HOST
which can be uniform across all vendors. As part of this refactor, we will be moving towards a model where only xcvrd interacts with the cables/transceivers,  and host-side processes will communicate with xcvrd rather than with the devices directly with Y-Cable. 
Ran the changes on Arista7050cx3 switch, making changes inside the container.

[xcvrd] initial support for integrating vendor specfic class objects for calling Y-Cable API's inside xcvrd

---

sonic-chassisd/scripts/chassisd

Fix a bug coming from https://github.com/Azure/sonic-platform-daemons/pull/175 when asic is removed due to card getting offline (before it was online).
The change works on real hw + unit test.

Fix a bug at removing asics on not-online cards

---

sonic-xcvrd/tests/test_xcvrd.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Due to rare timing issue test_sfp_insert_events failure can fail. Out of 100 iterations, the test failed on 82nd iteration.
Fix unit test failure:-
[https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/36875/logs/20](https://dev.azure.com/mssonic/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/36875/logs/20)
All 100 iterations of test_xcvrd.py now pass

Fix occassional test_sfp_insert_events failure

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR refactors the listening of port probes from linkmgr to xcvrd as so that xcvrd does not see timeout messages like these below
`Sep 27 22:24:37.490921 SONIC WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:815 handleMuxWaitTimeout: Ethernet120: xcvrd timed out responding to linkmgrd, current state: (P: Unknown, M: Wait, L: Down)`
Refactoring to a separate listener thread mode as well as removing the lock(safe because read/write transaction via eeprom for port probe) seems to handle this, and does not have the logs like this one above.
as the read write eeprom also has a mutex lock in the platform api call, optoe implementation.
https://github.com/Azure/sonic-linux-kernel/blob/889d76e36b3f012d3782a1c5e1587c32e4d1ed11/ …

[xcvrd][y_cable] refactor xcvrd to listen to port probe without locks; fix the get_firmware_version API to sync with download_firmware

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

Update line card thermal sensor status to DB, includes PSU thermal sensors and SFP thermal sensors on line card. Depends on https://github.com/Azure/sonic-buildimage/pull/8422.
In thermal update function, update PSU, SFP and direct thermal of line card
To support modular chassis
1. Full platform regression, 100% passed
2. Unit test passed

[thermalctld] Update line card thermal sensor status to DB

---

sonic-xcvrd/xcvrd/xcvrd.py

With new xcvr package, xcvrd fails to set pre-emphasis settings 
Return types has to be handled properly in xcvrd while handling media settings.
Tested in DellEMC Z9332f platform.
[cable_len_UT.txt](https://github.com/Azure/sonic-platform-daemons/files/7494484/cable_len_UT.txt)

Failed to set Pre-emphasis settings with new xcvr package

---

sonic-xcvrd/xcvrd/xcvrd.py

Changes to skip loading media_settings.json in case of fast-reboot
During fast-reboot, delayed serdes programming done after transceiver detection results in additional interface flap and traffic loss exceeding the required 30s (Issue: https://github.com/Azure/sonic-buildimage/issues/9165). This is addressed by making a backup of media settings from appdb during fast-reboot (https://github.com/Azure/sonic-utilities/pull/1910) and loading this to redis after the switch boots up (https://github.com/Azure/sonic-buildimage/pull/9166). Configuration of serdes triggered by reading media_settings.json file is skipped in this PR
Verified by running advanced_reboot/test_advanced_reboot.py::test_fast_reboot and ensured that the test passes.
Verified TRANSCEIVER_INFO in stateDB, SERDES objects in …

Skip loading media config from media_settings.json for fast-reboot

---

sonic-xcvrd/xcvrd/xcvrd.py

Changes to skip loading media_settings.json in case of fast-reboot
During fast-reboot, delayed serdes programming done after transceiver detection results in additional interface flap and traffic loss exceeding the required 30s (Issue: Azure/sonic-buildimage#9165). This is addressed by making a backup of media settings from appdb during fast-reboot (Azure/sonic-utilities#1910) and loading this to redis after the switch boots up (Azure/sonic-buildimage#9166). Configuration of serdes triggered by reading media_settings.json file is skipped in this PR
Verified by running advanced_reboot/test_advanced_reboot.py::test_fast_reboot and ensured that the test passes.
Verified TRANSCEIVER_INFO in stateDB, SERDES objects in asicdb after bootup
Also tested coldboot and ensured no side effects.

[202012] Skip loading media config from media_settings.json for fast-reboot

---

sonic-xcvrd/xcvrd/xcvrd.py

while doing a submodule update there could be a regression if we init/deinit xcvrd because of typo.
In order to ensure smooth init and deini of xcvrd we need the change. 
```
Nov 16 22:41:41.721557 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/bin/xcvrd", line 8, in <module>
Nov 16 22:41:41.722365 sonic INFO pmon#/supervisord: xcvrd     sys.exit(main())
Nov 16 22:41:41.722945 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1593, in main
Nov 16 22:41:41.723022 sonic INFO pmon#/supervisord: xcvrd     xcvrd.run()
Nov 16 22:41:41.723066 sonic INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1519, in run
Nov 16 22:41:41.723117 sonic INFO pmon#/supervisord: xcvrd …
```

[xcvrd] Fix Typo for initialization of post_sfp and deinit for xcvrd

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

Clear all data from DB table when the daemon stops
Clean up when the daemon stops
Check Thermal and physical info data if they are cleared after stopping the thermalctld.

Clear all data from DB table when the daemon stops

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

With new SFP refactor, hardware_rev is replaced with Vendor_rev key.
Made the changes in alignment with https://github.com/Azure/sonic-mgmt/pull/4816
xcvrd may crash for platform vendors as hardware_rev key is used in place of vendor_rev key.
Tested in DellEMC Z9332f platform.

[SFP-Refactor] Fix vendor  revision key issue

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Signed-off-by: Dante Su <dante.su@broadcom.com>
Add initial support for CMIS application initialization
Add CmisManagerTask to handle the per-port CMIS application initialization in parallel
1. Bring up Quanta IX9 with the default configuration and CMIS 4.0/5.0 QSFPDD modules
2. Issue 'show logging xcvrd' to check if the application initialization succeeded
3. Issue 'show interfaces transceiver eeprom --dom' to verify both the static and DOM information parsers
4. Issue 'sudo sfputil show eeprom --dom' to verify both the static and DOM information parsers
<table>
<tr>
<th>Repo</th>
<th>PR title</th>
<th>State</th>
</tr>
<tr>
<td>SONiC</td>
<td><a href='https://github.com/Azure/SONiC/pull/876'>[sfp-refactoring] Initial support for CMIS application initialization</a></td>
<td><img …

[sfp-refactoring] xcvrd: add initial support for CMIS application initialization

---

azure-pipelines.yml

…
During a recent cleanup of py2 wheels the path where dependent wheels are installed has changed.
This PR corrects that issue and gathers the dependency wheels from right path. 
To make sonic-platform-daemons build pass
pipelines need to pass

[sonic-platform-daemons] fix dependency issue on azure-pipelines by correcting the  path to gather wheel

---

sonic-ledd/scripts/ledd

Prevent ledd crash when an event on recirc port happens
A recirculation port is not a physical interface tied to a xcvr
Calling the led change event on such a port could lead to a ledd crash
This change was applied to running switch with its dependency https://github.com/Azure/sonic-buildimage/pull/9471
Verified that ledd runs without crashing
Cherry-pick required for 202106

[ledd] prevent ledd crash on recirc port event

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

xcvrd_utilities/port_mapping class returns the port_mapping_data info which includes internal ports. Internal port doesn't have transceiver. It should not be in the list for the xcvrd.
Issue -- https://github.com/Azure/sonic-buildimage/issues/9505
This commit adds code to check and skip internal port if a port is either Backplane or Inband port.  
This change will skip the internal port so that will trigger the exception in the XCVRD.
https://github.com/Azure/sonic-buildimage/issues/9505
Boot up the VOQ linecard.  Verify there is no such exception in syslog

[voq][pmon]xcvrd process show backtrace in the syslog on  VOQ linecard.

---

sonic-psud/scripts/psud
sonic-psud/tests/test_DaemonPsud.py
sonic-psud/tests/test_PsuStatus.py

1. Set PSU status default to True
2. Add PSU index to PsuStatus to help print the log with PSU id
Issue flow:
1. PSU is in bad state (e.g. PSU is not present, PSU is powered off, PSU overheat and so on)
2. psud startup
3. There is no warning logs in syslog
This PR is aimed to fix the issue
1. Manual test
2. Adjusted unit test

[psud] psud should log warning if PSU is in bad state before psud start up

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR refactores some of the message handling for CLI transacations by ycabled for muxcable
Particularly these CLI commands handling is refactored
```
show mux hwmode mux <port>
show mux hwmode switchmode <port>
config mux hwmode state <port>
config mux hwmode setswitchmode <port>
config mux firmware download/activate/rollback <port>
show mux firmware version <port>
```
With this PR all these notifications will be covered by Unit-Tests in our code
This PR is required to increase the code coverage of ycabled and attain a coverage of > 75%
This PR also removes refactors some code blocks which were not covered by UT
Ran the Unit-tests to the corresponding changes

[ycabled] increase UT coverage of ycabled daemon

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

(Porting PR233 to branch 202111)
xcvrd_utilities/port_mapping class returns the port_mapping_data info which includes internal ports. Internal port doesn't have transceiver. It should not be in the list for the xcvrd.
(Due to the code base is different, cherry-pick cannot be done) 
This change will skip the internal port so that will trigger the exception in the XCVRD.
Boot up the VOQ linecard. Verify there is no such exception in syslog

[pmon][xcvrd] Porting PR233 -- xcvrd process show backtrace on the internal port

---

sonic-psud/scripts/psud
sonic-psud/tests/test_PsuChassisInfo.py

On first run, the PSU master-led on supervisor of modular-chassis is not set. 
The PSU master-led on modular chassis indicates the power-buget status. Similar to individual PSU leds that are set on first_run, the master-led also will be set to based on initial status (RED or GREEN with LED status ON).
Without the forced setting of first_run, the master-led status will default to per vendor default. In some cases, this could be amber blinking etc
This has been tested on real HW and unit-tests using pytest suite.
```
tests/test_DaemonPsud.py::TestDaemonPsud::test_signal_handler PASSED                              [  3%]
tests/test_DaemonPsud.py::TestDaemonPsud::test_run PASSED                                         [  6%]
tests/test_DaemonPsud.py::TestDaemonPsud::test_update_psu_data …
```

Modular chassis: Psud set master led on first run

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes the MUX_CABLE_INFO table insertion logic which was not done before this PR. If the muxcable is plugged in, with this change if the config DB states that it is a muxcable then the logic populates the MUX_CABLE_INFO with 'N/A' or 
'unknown' entries. This was not done before
This PR also fixes the read_side logic, which if initialized with a -1 value would never be updated to the correct value, this PR makes sure that if the read_side is read correctly if cable not powered on/disconnected from server side, and the read_side is populated correctly in state DB. Before this change the read_side was not populated correctly if the cable was not powered from server side/disconnected. 
Required for the logic of services looking for …

[ycable] fix the logic to update cable_info values when ycable is not present; fix read side logic for ycable

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Add signal handlers correctly and fix clean up so that the auto restart works ok on signals.
Add signal handlers correctly and fix clean up so that the auto restart works ok on signals.
Verified by running again chassis LC.
```
jujoseph@014cbe230674:~/CHASSIS/CHASSIS/sonic-mgmt-int/sonic-mgmt-int/tests$ ./run_tests.sh -c platform_tests/daemon/test_chassisd.py -n vms29-t2--1 -d str2--lc2-1 -i "../ansible/str2,../ansible/veos" -t "t2,any" -e "--skip_sanity" -u
=== Running tests in groups ===
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography.exceptions import …
```

Fix platform daemon chassisd to handle auto restart on fail

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix Azure/sonic-buildimage#10530
Fix checkReplyType failed issue via recreating xcvr_table_helper on forking subprocess
In a rare scenario, `xcvrd` can fail due to the following exception:
```
xcvrd Traceback (most recent call last):
xcvrd   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
xcvrd     self.run()
xcvrd   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
xcvrd     self._target(*self._args, **self._kwargs)
xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 1140, in task_worker
xcvrd   File "/usr/local/lib/python3.7/dist-packages/xcvrd/xcvrd.py", line 548, in del_port_sfp_dom_info_from_db
xcvrd     dom_tbl._del(port_name)
xcvrd   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 2474, in …
```

Fix checkReplyType failed issue via recreating xcvr_table_helper on forking subprocess

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

This is to backport #255 to 202111 branch
Signed-off-by: Stephen Sun <stephens@nvidia.com>

[202111] Fix checkReplyType failed issue via making xcvr_table_helper from a global to a class member

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

This PR intends to include the recent changes made in the following two PRs from sonic-platform-common into transceiver_info table in state_db in xcvrd.py file.
https://github.com/Azure/sonic-platform-common/pull/228
https://github.com/Azure/sonic-platform-common/pull/235
The update transceiver info can be referenced to the HLD [here](https://github.com/Azure/SONiC/blob/9a350f6881b5c9609ba07425862e2c1b689c41e1/doc/platform_api/CMIS_and_C-CMIS_support_for_ZR.md#211-transceiver-info-table).
The old xcvrd was using sonic-platform-common that does not support CMIS and C-CMIS memory mapping. After we introduce the support for CMIS and C-CMIS memory map in xcvr_api in sonic-platform-common, we want to adopt the changes in xcvrd by starting with updating the transceiver_info table. After update, …

Include changes from xcvr_api in transceiver_info table

---

sonic-xcvrd/scripts/xcvrd

Ensure Xcvrd close the unused socket to prevent memory leak. Unix socket cannot drain the data if the listener is NOT consuming the data so we ensure to close the unused socket by Xcvrd. Xcvrd opens the connection to listen to PORT_TABLE of APPL_DB and later on leaves the socket open.
Monit service complains of crossing the expected threshold for memory usage by database container as below:
```
Oct 17 01:05:10.970410 SONIC-T0 ERR monit[538]: 'container_memory_database' status failed (3) -- [database] Memory Usage (1.57391e+08 Bytes) is larger than the threshold (157286400 Bytes)!
```
The following shows which redis-db client is using the memory:-
```
GECHIANG@SONIC-T0:/var/log$ redis-cli client list | grep -v omem=0
id=613 addr=127.0.0.1:42212 fd=288 name= age=30229173 idle=27168066 …
```

Mem leak caused by Xcvrd in Send-Q of REDIS-DB socket connection

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR is meant to do two fixes.
1) For the Y-cable if presence is missing, currently there is no provision for posting the MUX_CABLE_STATIC_INFO, this PR puts in that fix.
2) ycabled now utilizes the MUX_CABLE_TABLE:<port> to be notified/prepared to toggle the mux and blocks all ongoing i2c telemetry transactions which could be concurrently running. This PR utilizes a support  for adding a mux_toggle_status variable inside the base class for mux_cable.
Using this variable the Derived classes for mux_cable can check this and return in case of a mux_toggle_status is in progress.
From the higher layer this allows ycabled to synchronize the calls and not let mux_cable toggle to go in conjunction with some of the Telemetry calls.
3) also added a commented sub-routine to poll the mux …

[ycabled] fix the posting for mux_cable_static_info per downlink when ycabled is spawned; synchronizing executing Telemetry API

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds some improvement logic to ycabled daemon
1. correct the loopback IP's for active-active cable type for libra gRPC read_side establishment
2. improves the code for timeout value injection for different RPC's for gRPC
3. for cli HW_STATUS the daemon tries to use cached old value, if not present try to do RPC for getting ForwardingState with timeout of 0.1 ms
Required for gRPC logic improvement in few active-active scenario's
UT and deploying the changes in actual testbed

[sonic-ycabled] fix grpc logic for timeout,cli HWSTATUS value retrival logic for active-active cable

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

Since linkmgr/orchagent relies on ycabled to populate the mux_cable entries in the `HW_MUX_CABLE_TABLE`, for the cable `active-active` type this is accomplished by putting an unknown value if gRPC is unavailable, otherwise a normal RPC is used to query this and the response `active` or `standby` is written is `HW_MUX_CABLE_TABLE` table with a timeout.
This Fix accomplishes putting an `unknown/active/standby` to `state` key when ycabled starts
Unit-Tests and deploying the changes on testbed

[ycabled] Fix the init values for active-active ports

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Improved 400G link bring up sequence [HLD](https://github.com/sonic-net/SONiC/blob/master/doc/sfp-cmis/Interface-Link-bring-up-sequence.md)
1. Ensure CMIS compliant transceiver Datapath are initialized and activated IFF the host Tx signal is good and admin_status is UP
2. get_all_namespace() API is not reentrant resulting in crash, so we cache the namespace at the xcvrd start
3. Datapath is deactivated if either 'admin_status' becomes down or 'host_tx_ready' signal becomes OFF.
4. An option "--skip_xcvrd_cmis_mgr" is added to skip launch of CMIS task manager for platforms that are in transition to using SFP-refactor code 
5. Datapath is NOT impacted if Xcvrd crash/restarts
Deterministically improve the link bring up of 400G link that are using CMIS compliant transceivers.
Tested on 
1. …

[CMIS]Improved 400G link bring up sequence

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds support for creating a secure channel for gRPC between SOC and SONiC.
the certs and configurations are defined in config DB 
```
config': {
'type': 'secure',
'auth_level': 'server',
'log_level': 'info'
},
'certs': {
'client_crt': path',
'client_key': 'path
'ca_crt': 'path,
'grpc_ssl_credential': 'target override'
}
```
Using this config parameter we can have secure/insecure as well as mutual/server level authentication between SoC and SONiC.
This PR leverages the cert API's in gRPC lib and certs created to create a TLS based handshake if required to setup gRPC channel
Required for secure gRPC support between SONiC and SoC
Unit-Tests and running the changes on the testbed

[ycabled] add secure channel support for grpc dualtor active-active connectivity 

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

400G ZR configuration support
400G ZR needs configuration changes for laser frequency and Tx target output power
Xcvrd honors the configuration changes for both Tx power and laser frequency:
1. When Xcvrd is running
2. When Xcvrd comes up 
```
root@sonic:~# sfputil show eeprom -d -p Ethernet0
Ethernet0: SFP EEPROM detected
Active App Selection Host Lane 1: 1
Active App Selection Host Lane 2: 1
Active App Selection Host Lane 3: 1
Active App Selection Host Lane 4: 1
Active App Selection Host Lane 5: 1
Active App Selection Host Lane 6: 1
Active App Selection Host Lane 7: 1
Active App Selection Host Lane 8: 1
Active Firmware Version: 61.20
Application Advertisement: {1: {'host_electrical_interface_id': '400GAUI-8 C2M (Annex 120E)', 'module_media_interface_id': '400ZR, DWDM, amplified', …
```

Xcvrd changes to support 400G ZR configuration

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR provides a capability to sonic-utilities CLI to enable/disable telemetry for ycabled.
Basically there is a periodic loop for ycabled which posts telemetry data for that configured interval of time(currently 60 sec). This PR diables this data posting, and does not call platform API calls for ycable.
This PR is required for the initiative of getting some failover/switchover not get interfered because of sonic-telemetry API calls.
The CLI for enabling/disabling telemetry is
``` config muxcable telemetry enable/disable```
UT and deploying changes on Arista testbed
dependent on https://github.com/sonic-net/sonic-utilities/pull/2297 and submodule update

[ycabled] add capability to enable/disable telemetry

---

sonic-psud/scripts/psud
sonic-psud/tests/mock_platform.py
sonic-psud/tests/test_DaemonPsud.py

Signed-off-by: orfar1994 <orfar1994@gmail.com>
Add PSU input voltage, input current and max power to the PSU table in the STATE DB
psud would collect input voltage, input current and max power (capacity) of the PSU.
till now, it collect the output voltage and current.
more information about the PSU.
unit tests, manual testing.

add psu input voltage and current

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

Fixes: https://github.com/sonic-net/sonic-linkmgrd/issues/101
`ycabled` failed to toggle peer forwarding state for `active-active` ports.
Use `ConsumerStateTable` to listen to `HW_FORWARDING_STATE_PEER`.
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>
As the description
On a `dualtor-mixed` testbed, shutdown a port on upper ToR, verified the lower ToR could toggle the `nic_simulator` upper ToR forwarding state to `standby`.

Correct the peer forwarding state table

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

For Ports which do not belong to `active-active` or `active-standby` type, we should not try to post muxcable telemetry information for them. This PR remove the warning message for such a posting.
Also fixes the PR pipeline by changing the ConsumerTable to SubscriberStateTable
Unit-tests

[ycabled] remove some spurious logs

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes the portID sent for gRPC probing to the SoC/NIC-Simulator, and defaults it to `[0,1]`. 
This helps improve the logic and readibility of the logs as well for easier debug and response parsing is also improved
This PR also enables sonic-telemetry logging for `active-active` cable type
running the changes on testbed and UT

[ycabled] enable telemetry for 'active-active'; fix gRPC portid ordering

---

sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR intends to help fix the surplus amount of insert/delete events that ycabled gets it is first spawned, it fixes the logic where an insert event is only handled the way it is collected by `xcvrd` one time only. 
Previously there was  a known issue for spurious insert/delete events captured by ycabled on config reload, this PR fixes it
This PR also cleans up some mux toggle blocking other txns logic. 
Unit-tests and deploying changes on Testbed

[ycabled] fix insert events from xcvrd;cleanup some mux toggle logic

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR attempts to remove this call
`channel_ready = grpc.channel_ready_future` for the ycabled gRPC implementation. The reason to do this is incase of channel not being connected ycabled tries to reattempt the channel creation again with each RPC request from linkmgrd. 
This is not the right way to maintain the channels/stubs, and actually adds unrequired overhead for ycabled. This PR supports creating channel/stub in ycabled in correct manner. 
Required to reduce CPU usage for ycabled
Deploying the changes on Arista testbed and UT

[ycable] cleanup logic for creating grpc future ready

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Xcvrd should be listening to 
CONFIG_DB - For changes to speed, lane mapping, tx_power, frequency, admin_status
STATE_DB - For optics insertion/removal, host_tx_ready
APPL_DB - only during start to know if PortConfigDone is completed
Duplicate events are now soaked such that only the last event in a barrage of duplicate events is considered for further processing. Also, if a filter is installed then filter events having fields of interest that got changed from last time.
Portmgrd is writing unmodified fields to the APL_DB whenever there is configuration change resulting in too many event updates causing CMIS task manager that listens to these events to be woken up and restart the state machine unnecessarily. 
There can be events like port operationally going up in STATE_DB's PORT_TABLE …

[Xcvrd] Soak duplicate events and process only updated interested events

---

sonic-xcvrd/xcvrd/xcvrd.py

Signed-off-by: anamehra <anamehra@cisco.com>
The config db dictionary may not have admin_status available for a
port if the same is not set in config db file. Use get() function to
prevent crashes and set the default status to 'down'.
xcvrd crash is observed during boot on multi-asic chassis system.
The crash is reported in https://github.com/sonic-net/sonic-buildimage/issues/11707
On debugging the issue, found that at the point of the crash, the data being used is from config db.
It was observed that the Ethernet ports, which are not configured for admin_state field explicitly in the config  is causing the crash. This is a valid config as admin_status is not a mandatory field and is considerd by default 'down' if missing in port config in config db file.
for example, the Ethernet31 is …

Use get() to fetch default value from dictionary for port admin_status 

---

azure-pipelines.yml

sonic-swss-common lib will add dependency to libyang soon, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.

Install libyang to azure pipeline

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

For the cases where gRPC connectivity to server becomes IDLE/TRANSIENT_FAILURE, the ToR should periodically query/retry establish admin state and revert the Forwarding state back to active-active for both the T0's
This PR tries to attain that via adding a transient failure message to APP DB when connectivity is lost, so each time connectivity state changes back to not desired state(IDLE/TRANSIENT_FAILURE) we log a message, and linkmgr will query again to get gRPC in sync
Unit-tests and deploying changes to testbed

[ycabled] add notification for gRPC connection state transitions to  IDLE/TRANSIENT_FAILURE

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR does two main things
- It adds the capability for SONiC CLI to call  few API's like operationtime, healthcheck, queue_info, reset cause for it to be displayed via CLI
-  It adds a datetime field inside MUX_CABLE_INFO helpful for tracking last update, and it removes some of the toggle synchronization logic for SONiC telemetry, since SONiC telemetry table MUX_CABLE_INFO is anyways disabled/enabled using CLI 
```config muxcable telemetry enable/disable```, it is redundant to have this logic embedded in ycabled and port_instance helper objects,  which could be unneccessary
Putting the changes on Arista testbed and UT

add support to execute new ycable API's, add datetime field to mux_info

---

sonic-pcied/tests/mocked_libs/sonic_platform_base/sonic_pcie/pcie_common.py
sonic-xcvrd/xcvrd/xcvrd.py

Signed-off-by: maipbui <maibui@microsoft.com>
`subprocess()` - use `shell=False`, use list of strings Ref: [https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation](https://semgrep.dev/docs/cheat-sheets/python-command-injection/#mitigation)
`subprocess()` - when using with `shell=True` is dangerous. Using subprocess function without a static string can lead to command injection.

Remove shell=True

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds support for adding the secrets to grpc client in `active-active` configuration via a shared file
`/etc/sonic/grpc_secrets.json`.
Using this file, secrets configuration in populated inside CONFIG_DB,
absence of this file will assume insecure gRPC client. 
testing with UT and putting the changes on Arista testbed

[ycabled] add support for getting grpc secerts via shared file

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds a try/catch block for some abstract muxcable API's. In particular the exception logic is added for all the API's where there is a possibility for exceptions to be passed by Vendor API's implementation, in this regard ycabled will have all abstract muxcable API's covered by exception logic with this PR.
If the exception is caught it will be just logged and daemon will resume its normal operation.
Unit-tests and deploying changes on testbed

[ycabled] add some exception catching logic to some vendor specific API's

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes a typo/error condition when read_side is not 1 or 2 or -1, for a case where NIC side is plugged into the ToR and a user configures a CLI for 
```sudo config mux hwmode state active/standby <port>```, 
in such a scenario we can trigger this 
xcvrd_config_hwmode_state_cmd_sts_tbl attribute error. 
Unit-tests and loading the changes on Arista testbed

[ycabled] fix naming error for error condition for CLI handling

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix Xcvrd code to support 400G ZR optic
While bringing the 400G ZR module, I found an issue where some 400G ZR optics may take more than 60 secs to finish up the Datapath initialization. This is a problem because the xcvrd uses a hardcoded 60 secs Datapath initialization timeout for all CMIS modules and apparently, this 60 secs timeout is not sufficient for the 400G ZR module.
The CMIS spec has Datapath init/de-init timeout values defined in Byte 144. We can use these values from the EEPROM instead of presenting any hardcoded values.
This is needed to bring up 400G ZR module.
These changes are tested against arista_7800r3a_36d2_lc and arista_7280cr3_32p4 platforms.

Fix xcvrd to support 400G ZR optic

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes and issue when gRPC listener acknowledges the request from ycabled but sends no ports/states in the response
Example for such responses :
```
Oct 19 21:38:32.643397 DEV NOTICE pmon#ycable[128076]: Set admin state RPC received response port Ethernet44 port ids = [] curr_read_side 0 read_side 1
Oct 19 21:38:32.643515 DEV NOTICE pmon#ycable[128076]: Set admin state RPC received response port Ethernet44 state values = [] curr_read_side 0 read_side 1
```
ycabled will write appropriate unknown/failure in such a case.

[ycabled] fix no port/state returned by grpc server

---

sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Signed-off-by: Mihir Patel <patelmi@microsoft.com>
Port link goes down when SWSS is restarted.
Issue
It seems that when SWSS restarts, the admin_status field in STATE_DB changes from 'up' to 'down' followed by going back to 'up' state again.
Following is the sequence of events
1. User restarts SWSS
2. Once SWSS is restarted, the STATE_DB sees that 'host_tx_ready' field has been added with a value true. This generates a on_port_update_event and triggers all data structures to be updated. While this happens, 'admin_status' in STATE_DB is down  and hence, xcvrd disables Tx due to this.
3. After sometime, 'admin_status' in STATE_DB is updated with the value 'up'. However, this doesn't generate an update since on_port_update_event is generated for STATE_DB only when there is a change with any …

Port link goes down when SWSS is restarted

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds a support for taking `detach` mode into consideration as a valid CONFIG_DB state for muxcable.
If 'detach' mode is configured it will be treated as a valid and appropriate RPC's will be serviced by ycabled. 
UT and deploying changes on testbed

[ycabled] add support for detach mode in 'active-active' topology

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py

This PR attempts for ycabled to have all 
```swsscommon.Table and daemon_base.db_connect```
as just a single call in the thread instance for all task_workers
For example all swsscommon calls to open Tables are moved as class object varables, which are reused when needed instead of opening the Table again in subroutines.
```
self.config_db[asic_id] = daemon_base.db_connect("CONFIG_DB", namespace)
```
This would help in avoiding unforeseen redis-errors
Deploying changes on testbed and UT

[ycabled] move swsscommon API's from subroutines to call them exactly once per task_worker/thread

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>
The following changes are done in chassisd
-  Change the `ModuleUpdater` init changed to include slot and supervisor as argument.
-  Add logic to in `ModuleUpdater` to update the asic_info in `CHASSIS_FABRIC_ASIC_INFO` for the supervisor and `CHASSIS_ASIC_TABLE` for the linecard asics respectively.
- Add the linecard name is the key of the `CHASSIS_ASIC_TABLE` 
- update the UT
Fixes https://github.com/sonic-net/sonic-buildimage/issues/12575 and https://github.com/sonic-net/sonic-buildimage/issues/12575
Update the pmon on the supervisor and linecard and verify the `CHASSIS_STATE_DB` is update properly
```
admin@str2-sonic-sup-1:~$ redis-cli -h redis_chassis.server -p 6380 -n 13 keys *ASIC*
1) …
```

[chassisd] update chassisd to write fabric and lc asics on seperate table in chassis state db

---

sonic-psud/scripts/psud
sonic-psud/tests/mock_platform.py
sonic-psud/tests/test_DaemonPsud.py

Support PSU power threshold checking
- Two platform APIs are introduced to represent the warning and critical thresholds of a PSU's power
- In the main loop
- Whenever a PSU becomes good, PSU daemon tries calling platform APIs to fetch both thresholds. If `None` is returned or `NotImplemented` is thrown by either API, the PSU power threshold checking will not be performed for the PSU
- the PSU daemon compares the power with thresholds, exposing status to the database, and logging messages.
To notify the user if the PSU's power exceeds the threshold.
Unit test cases have been implemented.

[PSU daemon] Support PSU power threshold checking

---

sonic-xcvrd/xcvrd/xcvrd.py

It seems that with the below PR, a new parameter "grid" was added to set_laser_freq function. However, xcvrd is not passing this parameter and hence, we are seeing an error while calling set_laser_freq function for 400ZR transceiver. This task will ensure that we resolve the current error seen.
PR which triggers the error
https://github.com/sonic-net/sonic-platform-common/pull/294
Error
```
Nov 28 21:19:28.258483 sonic INFO pmon#supervisord: xcvrd Process Process-1:
Nov 28 21:19:28.262677 sonic INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 28 21:19:28.262677 sonic INFO pmon#supervisord: xcvrd   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
Nov 28 21:19:28.262677 sonic INFO pmon#supervisord: xcvrd     self.run()
Nov 28 21:19:28.263290 …
```

Pass grid parameter while calling set_laser_freq

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes the app DB access fix logic by updating the values causing some failures for ycabled's response for mux probe from linkmgrd.
This PR essentially fixes that logic, calling the correct method to access the app DB
UT and deploying changes to kvm

[ycabled] fix minor appl_db retrieving logic for update

---

sonic-xcvrd/xcvrd/xcvrd.py

Signed-off-by: Vivek Reddy <vkarri@nvidia.com>
Fixed SfpStateUpdateTask to not crash during port_cfg dynamic add/del event
During port breakout, the subprocess invoked by parent xcvrd is crashing indicated by the following log:
```
Nov 24 15:40:03.572897 qa-eth-vt02-3-2700a0 INFO pmon#supervisord: xcvrd Process Process-1:
Nov 24 15:40:03.577327 qa-eth-vt02-3-2700a0 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 24 15:40:03.578223 qa-eth-vt02-3-2700a0 INFO pmon#supervisord: xcvrd   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
Nov 24 15:40:03.578478 qa-eth-vt02-3-2700a0 INFO pmon#supervisord: xcvrd     self.run()
Nov 24 15:40:03.579059 qa-eth-vt02-3-2700a0 INFO pmon#supervisord: xcvrd   File …
```

[xcvrd] Remove the extra argument that is causing the xcvrd crash

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

This PR is adding the required changes for creating a table for DOM threshold in state DB. Please refer to CMIS_and_C-CMIS_support_for_ZR.md document for field definitions for [TRANSCEIVER_DOM_THRESHOLD](https://github.com/sonic-net/SONiC/blob/master/doc/platform_api/CMIS_and_C-CMIS_support_for_ZR.md#213-transceiver-dom-threshold-table).
Overall, TRANSCEIVER_DOM_SENSOR DB table currently comprised of fields for TRANSCEIVER_DOM_SENSOR as well as TRANSCEIVER_DOM_THRESHOLD. With the current PR, a separate entry in state DB has now been created for TRANSCEIVER_DOM_THRESHOLD related fields.
The new command to display the threshold relevant fields will be done separately and is currently being tracked using https://github.com/sonic-net/sonic-buildimage/issues/12911.
PR …

Create TRANSCEIVER_DOM_THRESHOLD table in state DB

---

sonic-xcvrd/tests/mock_swsscommon.py
sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Add new fields to status/dom_sensor/pm tables in STATE_DB for CMIS/C-CMIS
1. Add all the fields that are supported by c_cmis [get_transceiver_bulk_status](https://github.com/sonic-net/sonic-platform-common/blob/b26aa5ef79fca95064d0baf3b1beed8d56d212f8/sonic_platform_base/sonic_xcvr/api/public/c_cmis.py#L302) API but not currently present to dom_sensor table.
2. Add new fields (provided by [cmis.py:get_transceiver_status() API](https://github.com/sonic-net/sonic-platform-common/blob/86bab38c723eb4ebbfa16feed66344d1b3ffd46e/sonic_platform_base/sonic_xcvr/api/public/cmis.py#L1548) and [c_cmis.py:get_transceiver_status() API](https://github.com/sonic-net/sonic-platform-common/blob/86bab38c723eb4ebbfa16feed66344d1b3ffd46e/sonic_platform_base/sonic_xcvr/api/public/c_cmis.py#L565) ) to status …

Add new fields to status/dom_sensor/pm tables in STATE_DB for CMIS/C-CMIS

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

This PR aims to get rid of such messages in syslog when thermalctld, essentially delete keys is getting called twice, causing some redis issues.
This PR gets rid of deleting such keys twice.
Nov 16 00:33:00.566174 sonic INFO pmon#/supervisord: thermalctld Exception ignored in: <function TemperatureUpdater.__del__ at 0xb5dbe810>
Nov 16 00:33:00.566585 sonic INFO pmon#/supervisord: thermalctld Traceback (most recent call last):
Nov 16 00:33:00.566825 sonic INFO pmon#/supervisord: thermalctld   File "/usr/local/bin/thermalctld", line 558, in __del__
Nov 16 00:33:00.567014 sonic INFO pmon#/supervisord: thermalctld     table_keys = self.table.getKeys()
Nov 16 00:33:00.567181 sonic INFO pmon#/supervisord: thermalctld   File …

[thermalctld] fix some redundant removal of state DB tables

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Added a call to the `self.on_add_logical_port()` method when handling `PORT_ADD` event in `class SfpStateUpdateTask`.
This call was removed in commit 94fa239a, which caused transceiver info to be missing after port breakout change.
Fix bug where transceiver info is missing after port breakout change.
Apply port breakout and ensure transceiver info exists for each sub-port.

Fix bug where transceiver info is missing after port breakout change

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/mocked_libs/sonic_platform/__init__.py
sonic-chassisd/tests/mocked_libs/sonic_platform/chassis.py
sonic-chassisd/tests/mocked_libs/sonic_platform/platform.py
sonic-chassisd/tests/test_chassisd.py

Do an explicit task stop of config_manager task in the chassisd 
Fixes issue https://github.com/sonic-net/sonic-buildimage/issues/11955
Updated the test_chassisd.py as per https://github.com/sonic-net/sonic-mgmt/pull/7150 and made sure it is a consistent PASS

Chassisd do an explicit stop of the config_manager

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Make all task workers as child thread of main process. 
The main process should watch for any child thread crash and do suicide to restart itself. Also ensure the backtrace of crashing child thread is shown
Overall, the change set now adheres to a template for creating thread and handles exceptions followed by restarting xcvrd.
With this change set, 3 threads will be created:
1. CmisManagerTask (This was formerly a process)
2. DomInfoUpdateTask (This already exists as a thread)
3. SfpStateUpdateTask (This was formerly a process)
All the above threads have now been named accordingly.
Once an exception is raised, the run() method will generate a traceback and will set the main_thread_stop event.
The xcvrd daemon keeps waiting until main_thread_stop event is generated. Once this event is …

Xcvrd should restart if any child thread crashes

---

sonic-xcvrd/setup.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Fixed optics insertion/removal not detected by Xcvrd.
The key to port_mapping.get_physical_to_logical() expects integer. Otherwise, on OIR events, Xcvrd throws the below error and misses processing of OIR events
```
/var/log/syslog.169.gz:Nov 29 19:21:47.275665 3POs-7050CX-T1-H06-39 WARNING pmon#xcvrd[42]: Got unknown FP port index 29, ignored
/var/log/syslog.169.gz:Nov 29 19:21:52.309169 3POs-7050CX-T1-H06-39 WARNING pmon#xcvrd[42]: Got unknown FP port index 30, ignored
/var/log/syslog.180.gz:Nov 29 16:30:14.687024 3POs-7050CX-T1-H06-39 WARNING pmon#xcvrd[43]: Got unknown FP port index 11, ignored
/var/log/syslog.180.gz:Nov 29 16:30:24.780574 3POs-7050CX-T1-H06-39 WARNING pmon#xcvrd[43]: Got unknown FP port index 16, ignored
/var/log/syslog.180.gz:Nov 29 16:30:31.850078 …
```

[Xcvrd]: Fix optics insertion/removal not detected

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR adds logic to add the following gRPC relevant telemetry schema fields in the state DB  table
`MUX_CABLE_INFO`
```
1) "self_link_state"
2) "up"
3) "peer_link_state"
4) "up"
5) "self_oper_state"
6) "up"
7) "peer_oper_state"
8) "up"
9) "server_version"
10) "1.0"
11) "grpc_connection_status"
12) "READY"
13) "self_mux_direction"
14) "active"
15) "peer_mux_direction"
16) "active"
17) "peer_mux_direction_probe_count"
18) "23"
19) "mux_direction_probe_count"
20) "23"
21) "link_state_probe_count"
22) "1"
23) "peer_link_state_probe_count"
24) "1"
25) "operation_state_probe_count"
26) "1"
27) "peer_operation_state_probe_count"
28)"1"
```
This data will allow telemetry to check gRPC stats and version of the server and be able to raise …

add data for telemtery enhancement for 'active-active' cable type

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

The main motivation of this PR is improve coverage of ycabled.
While fixing unit  test cases found an improvement to the name key-values returned to CLI, changed those names for keys as well
Unit-Tests and running the changes on testbed.

[ycabled] add more coverage to ycabled; add minor name change for vendor API CLI return key-values pairs

---

sonic-xcvrd/xcvrd/xcvrd.py

Updating module types to support 2x100G AOC
It seems that the CMIS module type for 2x100G AOC was not part of CMIS_MODULE_TYPES in xcvrd. This PR has added the corresponding type (QSFP+C) for it
Verified that 2x100G AOC is detected and CMIS init code is triggered

Update CMIS module types for 2x100G AOC support

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This change creates `unknown, N/A` values for `active-standby` cable types for `active-active` type cable.
Since streaming telemetry today looks for both `active-active` and `active-standby` for posting values to State DB, this change introduces a  one time posting of fields with 'pseudo-cable' type when channels are attempted to be created by ycabled.
UT and posting the changes on test device.

[ycable] add changes for correcting telemetry values for 'active-active'

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Code changes are implemented in deinit function such that it does not remove entries in CHASSI_FABRIC_ASIC_TABLE when supervisorctl stop chassisd is triggered.
fixes https://github.com/sonic-net/sonic-buildimage/issues/13559: The container_cheaker depends on CHASSIS_FABRIC_ASIC_TABLE to provide the available asic list to calculate the expected dockers but as pmon is down and the table is cleared from chassis db, asic information is not present. Due to this, container_checker does not include the swss, syncd, teamd services in the expected docker list and fails to report the error.
1) Execute the below cmd.
```
admin@supervisor:~$docker exec pmon supervisorctl stop chassisd
chassisd: stopped
```
2) Look for the table entries using below cmd.
```
admin@supervisor:~$ sonic-db-dump -n …
```

Fixed chassis: test_container_checker failure for swss/syncd/teamd on multi-asic Supervisor - issue #13559

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

This PR is similar to https://github.com/sonic-net/sonic-platform-daemons/pull/335, dedicated to 202205 branch.
Update xcvrd to check if fast-reboot is enabled according to the new value for FAST_REBOOT entry in STATE_DB.
This PR should come along with the following PRs:
https://github.com/sonic-net/sonic-buildimage/pull/14143
https://github.com/sonic-net/sonic-sairedis/pull/1217
https://github.com/sonic-net/sonic-utilities/pull/2724
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
Description
Update xcvrd to check the updated form of fast-reboot entry in state-db as it was changed.
Motivation and Context
Introducing fast-reboot finalizer on top of warmboot-finalizer, fast-reboot entry in STATE_DB is now changed from "1"/None to "enable: …

[202205] Update xcvrd to use new STATE_DB FAST_REBOOT entry

---

azure-pipelines.yml

1. Upgrade docker env to bullseye.
2. Upgrade .NET to 7.0 to match bullseye.

[ci] Upgrade docker env to bullseye.

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py

Set the `config_manager` variable to `None` if we are running on a linecard and thus don't need to set up the config manager.
During cleanup, the chassid service tries to clean up the `config_manager`, but the `config_manager` variable is only ever initialized if we are on the supervisor. Thus, checking if it is `None` is insufficient because this results in an `UnboundLocalError` that prevents the cleanup from succeeding on a linecard.
This was tested via the sonic-mgmt `platform_tests/daemon/test_chassisd.py` test. Without this change, the `test_pmon_chassisd_stop_and_start_status` test would fail and a traceback would be present in syslog. The test passes with this patch applied.

chassisd: Fix crash on exit on linecard

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix issue https://github.com/sonic-net/sonic-buildimage/issues/14213.
https://github.com/sonic-net/sonic-platform-daemons/commit/56046dc36907c7e873911ef60e9193fe8717b12c introduces a race condition between DomInfoUpdateTask and SfpStateUpdateTask. In this PR, `SfpStateUpdateTask::on_add_logical_port` is changed to no longer depending on TRANSECIVER_STATUS table and always get SFP data from platform API.
Fix https://github.com/sonic-net/sonic-buildimage/issues/14213
Manual test
UT logs:
```
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-platform-daemons/sonic-xcvrd, configfile: pytest.ini
plugins: pyfakefs-5.1.0, cov-2.10.1
collecting ... collected 54 items …
```

Fix issue: Exception occured at SfpStateUpdateTask thread due to KeyError('status')

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

The changes with this PR needs to be merged along with sonic-net/sonic-platform-common#352
Currently, xcvrd has a fixed logic to calculate active host lanes for a port. This needs to be changed to support ports with breakout cable.
The fixed host lane mapping will now be replaced by reading the subport from the CONFIG_DB. The subport will then be used to calculate active host lanes by reading the Application Descriptors.
Finding the desired application
The HostInterfaceID and HostLaneCount from Application Descriptors will be used to find the desired application for the port with breakout cable by comparing these with speed and lanes retrieved from CONFIG_DB.
Finding active host lane
Once the desired application is found, the HostLaneAssignmentOptions (bitmap of active host lanes) for the …

Retrieve subport from CONFIG_DB to enable breakout support

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Update xcvrd to check if fast-reboot is enabled according to the new value for FAST_REBOOT entry in STATE_DB.
This PR should come along with the following PRs:
https://github.com/sonic-net/sonic-utilities/pull/2621
https://github.com/sonic-net/sonic-buildimage/pull/13484
https://github.com/sonic-net/sonic-swss-common/pull/742
https://github.com/sonic-net/sonic-sairedis/pull/1196
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
Update xcvrd to check the updated form of fast-reboot entry in state-db as it was changed.
Introducing fast-reboot finalizer on top of warmboot-finalizer, fast-reboot entry in STATE_DB is now changed from "1"/None to "enable"/"disable".
Existing tests, and fast-reboot.

Update xcvrd to use new STATE_DB FAST_REBOOT entry

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

For Neo ZR, it can't do CMIS init due to timeout
```
Feb  1 10:58:10.936128 as9736-64d-2 NOTICE pmon#xcvrd: CMIS: Ethernet496: force Datapath reinit
Feb  1 10:58:12.032012 as9736-64d-2 NOTICE pmon#xcvrd: CMIS: Ethernet496: 100G, lanemask=0xf, state=DP_DEINIT, retries=2
Feb  1 10:58:13.476090 as9736-64d-2 NOTICE pmon#xcvrd: CMIS: Ethernet496 DpDeinit duration 5.0 secs
Feb  1 10:58:14.572104 as9736-64d-2 NOTICE pmon#xcvrd: CMIS: Ethernet496: 100G, lanemask=0xf, state=AP_CONFIGURED, retries=2
Feb  1 10:58:17.956000 as9736-64d-2 NOTICE pmon#xcvrd: message repeated 3 times: [ CMIS: Ethernet496: 100G, lanemask=0xf, state=AP_CONFIGURED, retries=2]
Feb  1 10:58:17.956000 as9736-64d-2 NOTICE pmon#xcvrd: CMIS: Ethernet496: timeout for 'ModuleReady'
```
For Neo ZR, the DpDeinit duration is 5 seconds …

[CMIS] Add power up duration for power up timeout

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Invoke tx_disable_channel() api using the correct media_lanes_mask in case of subport shut/no shut operations
(i.e) existing tx_disable_channel( ) api is being used with host_lanes_mask as of now.  
This is not aligning with the subport concept where media_lane start wont match with host_lanes start.
As part of the fix, introduced an api to retrieve media_lanes_mask and use it as part of the tx_disable_channel() api
Using 4x100G and 2x100G breakout modules 
-   create 4 and 2 subports on 4x100G and 2x100G modules respectively.
-   Check whether all the subports are operationally up 
-   Verify the upper page 10 for outputdisable values and page 11 for the data path state
-   Shut each subports one at a time and verify the operational status of every subports in this module
-   Unshut each …

Use tx_disable_channel with media_lanes_mask

---

sonic-ycabled/proto/proto_out/linkmgr_grpc_driver.proto
sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py

This PR adds an enhancement to ycabled when if and whenever a notification arrives from SoC or server that it is going to be serviced. The notification can come at anytime and hence it must be listened to or awaited by the client at all times. For this we use asyncio lib and avail the async functionality in python. 
the added code defines a GracefulRestartClient class that can be used to send requests to a gRPC server for graceful restart. The class has three async methods: send_request, receive_response, and notify_graceful_restart_start.
send_request method retrieves tor from request_queue, creates a request with the ToR, and sends it to the server using the stub's NotifyGracefulRestartStart method. It then reads the response from …

add async notification support in active-active topo; refactor code for ycable tasks for change events 

---

sonic-xcvrd/xcvrd/xcvrd.py

Upstream xcvrd issue: https://github.com/sonic-net/sonic-platform-daemons/issues/358
As per Media-based port settings [HLD](https://github.com/sonic-net/SONiC/blob/master/doc/media-settings/Media-based-Port-settings.md), if 'vendor_key = vendor_name + vendor_PN' lookup fails, then reduce 'vendor_key = vendor_name' and search again for media_settings.
Simply add Optics' vendor name in platform media_settings.json if the SI params apply to all modules for that vendor.
Added "<vendor_name>" media_settings (without vendor PN) for Cisco 8111 and validated that SI params were notified for all variations of <vendor_name> cables.
swss/sairedis snippet showing that xcvrd notified media_settings (based on "<vendor_name>" alone) to OA/syncd:
```
root@sonic:/home/cisco# grep idriver …
```

[xcvrd] Reduce vendor_key to vendor_name for media_settings lookup

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

Fixes: #361
Fix the tardy command `show mux status`:
```
Jun  5 08:07:20.524687 lab-device-01 ERR pmon#CCmisApi: Exception occured at child thread YcableCliUpdateTask due to TypeError("handle_show_hwmode_state_cmd_arg_tbl_notification() missing 1 required positional argument: 'port'") Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 4000, in run#012    self.task_cli_worker()#012  File "/usr/local/lib/python3.9/dist-packages/ycable/ycable_utilities/y_cable_helper.py", line 3864, in task_cli_worker#012    handle_show_hwmode_state_cmd_arg_tbl_notification(fvp, self.cli_table_helper.port_tbl, self.cli_table_helper.xcvrd_show_hwmode_dir_cmd_sts_tbl, self.cli_table_helper.xcvrd_show_hwmode_dir_rsp_tbl, …
```

[dualtor] Fix command `show mux status`

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes the other sub routine by adding the param `hw_mux_cable_tbl` to 
`handle_config_hwmode_state_cmd_arg_tbl_notification` method, since this is called by wrong params
UT and testing this on DUT

[ycabled] correct the wrong function call for 'config hwmode state'

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/test_chassisd.py

Enhancement request: https://migsonic.atlassian.net/browse/MIGSMSFT-209
- Add enhancement to the "show chassis modules status" CLI to see a new column added at the end to show each card's serial number
- Store another field - serial in chassis module table for each card, which is to be fetched and displayed for above CLI
- Dependent PR in sonic-utilities to accommodate the display for serial field, both PRs <363> and <2858> need to go together and submodule versions need to be updated 
(https://github.com/amulyan7/sonic-utilities/pull/1)
Expectation:
RP: CLI should display all fields (including serial) for all module types (Supervisor, Fabric card, Line card) that are present
LC: Useful to show self (LC) and Supervisor module to allow monitoring of operation status of the corresponding …

[show][chassis]: Add support for serial field to show chassis module status CLI

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/sfp_status_helper.py

It seems that currently, xcvrd consumes a lot of time (in the order of minutes) during the init phase to update the STATE_DB with information from transceiver EEPROM followed by spawning threads.
This initial update to state DB is a blocking call in the xcvrd main thread and hence, it increases the overall time to spawn threads. Hence, we need to ensure that CMIS init executes soon after xcvrd is spawned and parallelly proceed with STATE_DB updates with the relevant thread.
We also need to separate periodic v/s fixed EEPROM reads between threads to ensure that the DomInfoUpdateTask thread polls information from EEPROM which changes periodically and SfpStateUpdateTask updates STATE_DB with information which remains static after transceiver detection.
1. Ensuring EEPROM fields which require …

Separate periodic v/s fixed EEPROM reads between threads and optimize xcvrd boot-up time

---

sonic-psud/scripts/psud
sonic-psud/tests/test_DaemonPsud.py

Compare the system power instead of PSU power with the PSU's threshold.
On a system with more than one PSU, the power consumption will not distribute evenly on both PSUs, as a result, it gives a wrong message sometimes.
To fix the error, it should compare system power with the PSU's threshold.
Unit test
Manual test
Regression test

[PSU power threshold] Fix logic error: compare the system power with the PSU's power threshold

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/tests/test_ycable.py
sonic-ycabled/ycable/ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR intends to not start sonic-ycabled's Asynchronous client, when there is no active-active cable type.
The Problem that we encounter is ycabled expects all threads to be working/running state all the time. 
Since there are no `active-active` cable_type Async client thread  exits gracefully, 
but by design this needs to be working if added to monitor loop thread. So this PR fixes this problem by runnig the Async Client only if configuration is `active-active` for atleast a cable. 
This PR also has all the infrastructure changes UT for all Classes having infinite loops in ycabled, thus helping in picking up cases if changes break the code. 
Running on DUT and UT

[ycabled][active-active] no initialize Async Client, when no active-active cable type; fix names for all ycabled threads

---

sonic-pcied/scripts/pcied
sonic-pcied/tests/test_DaemonPcied.py

Added code to carry out PCI transactions with all the peripherals on the device. This is to determine if there are any unreachable devices on the PCIe bus. The gold list of PCI peripherals is a static file that varies depending on the platform. BDF information is parsed from this YAML file. Transactions are then carried out to determine the health of each peripheral.
Fixes: Generate syslog alert for missing PCIe devices
Manually disabled a PCI peripheral and verified that the code changes were able to pick it up:
```
admin@str-s6000-on-6:~$ lspci -tv
-[0000:00]-+-00.0  Intel Corporation Atom Processor S1200 Internal
+-01.0-[01]----00.0  Broadcom Inc. and subsidiaries Broadcom BCM56850 Switch ASIC
+-02.0-[02]----00.0  Marvell Technology Group Ltd. Device 9170 …
```

Added PCIe transaction check for all peripherals on the bus

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

Use vendor customizable fan speed threshold checks in thermalctld instead of hard-coded calculations based on pwm/percentage speed.
Fan under/over speed checks should be vendor customizable, since a tolerance based off the pwm/percentage fan speed can easily give false failures, especially for low fan speeds.
```
root@sonic:/home/cisco# echo 10000 > /opt/cisco/etc/fantray0.fan0.rpm
root@sonic:/home/cisco# grep thermalctld /var/log/syslog
<snip>
May 19 05:09:47.763970 sonic WARNING pmon#thermalctld: Fan high speed warning: fantray0.fan0 current speed=91, target speed=20
May 19 05:09:51.129298 sonic INFO pmon#supervisord 2023-05-19 05:09:51,128 INFO success: thermalctld entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
May 19 05:10:01.347935 sonic INFO …
```

Use vendor customizable fan speed threshold checks

---

sonic-pcied/scripts/pcied
sonic-pcied/tests/mocked_libs/swsscommon/swsscommon.py
sonic-pcied/tests/test_DaemonPcied.py

Fixes for the following issues:
- Lack of getKeys() impl in mock swsscommon table class in sonic-pcied
- Fixed a 'set' bug in pcied that was uncovered by new code flows
This PR fixes issues in pcied as well as mock implementations for unit tests that were uncovered by new code flows.
Recreated the new code flow with the changes and ensured that all the tests passed without exceptions

Fixes for the issues uncovered by sonic-pcied unit tests

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/mocked_libs/sonic_platform/__init__.py
sonic-chassisd/tests/mocked_libs/sonic_platform/chassis.py
sonic-chassisd/tests/mocked_libs/sonic_platform/platform.py
sonic-chassisd/tests/test_chassisd.py

Set the `config_manager` variable to `None` if we are running on a
linecard and thus don't need to set up the config manager.
During cleanup, the chassid service tries to clean up the
`config_manager`, but the `config_manager` variable is only ever
initialized if we are on the supervisor. Thus, checking if it is
`None` is insufficient because this results in an `UnboundLocalError`
that prevents the cleanup from succeeding on a linecard.
This has been tested via both the sonic-mgmt platform_tests test case
for the chassid daemon as well as the updated unit tests in this PR.
This is a cherry-pick of PR #347 to 202211 release branch. Note that
PR #328 is also backported to 202211 in this PR as it is required for the
unit test update to pass.

[202211] chassisd: Fix crash on exit on linecard

---

sonic-pcied/scripts/pcied
sonic-pcied/tests/mocked_libs/swsscommon/swsscommon.py
sonic-pcied/tests/test_DaemonPcied.py

This PR reverts the commit #331 which added a PCIe transaction check for all peripherals on the bus.
There are vendor-specific implementation details that warrant a refactor.
Reverted the changes, built image and verified that the revert was successful.

Revert pcied enhancements

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassis_db_init.py
sonic-chassisd/tests/test_chassisd.py

Following changes are done in this PR
- In line card pmon:chassisd:
- line card's hostname and number of asics is pushed to a new table CHASSIS_MODULE_TABLE in chassis state db in redis_chassis server. The hostname and number of asics are required to clean up chassis add db. 'hostname' and asic name are used to construct  key for chassis app db entries.
- In supervisor pomon:chassisd:
- When midplane connectivity loss is deteced, error syslog is generated. No chassis app db clean up is done for midplane connectivity loss.
- When a module goes down and if it is in down state for more than 30 minutes, chassis app db clean up is done for all the asics of the module that went down. As part of the clean up entries created by all the asics of the down module are deleted from the following …

[pmon] Chassis DB cleanup when module is down

---

sonic-chassisd/scripts/chassisd

Fix for issue https://github.com/sonic-net/sonic-buildimage/issues/16465
MSFT ADO: 25174518
Root cause:
- In the line card pmon, while pushing the hostname to CHASSIS_HOST_TABLE in chassis state db, the slot id is also pushed.     The slot id (self.my_slot) is not a string. Since the FieldValue construction function expects string values, the wrapper raises     value TypeError exception and hence chassisd exited.
Fix:
- Fixed by hard converting self.my_slot to string while passing the value to the FieldValue data construction function.
The changes in this PR fixes the chassisd crash reported by https://github.com/sonic-net/sonic-buildimage/issues/16465
- pmon with chassisd with the changes in the PR is loaded in a line card and the syslog was checked. 
- No chassisd crash was observed.
- …

[pmon]chassisd crash fix

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

Add dynamic sensor logic for fixed and psu presence/state checking in thermalctld. As requested, creating separate double commit for 202205 to address merge conflict.
Description
Extends the existing dynamic sensor logic of modular chassis to fixed and adds a check for PSU presence/status in thermalctld
Motivation and Context
In current form, if a PSU or other device with sensors is removed from the device or disabled during runtime on a fixed chassis, they will become stale and remain in the temperature sensor DB which should not be correct. This change brings the existing logic checks that modular chassis' have to fixed platform as well as checks for PSU presence/status to account for scenario where PSU may be disabled during runtime.
How Has This Been Tested?
On both fixed and modular …

Add dynamic sensor logic for fixed and psu presence/state checking in thermalctld, 202205 merge conflicts addressed

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

With the latest SONiC image, the link on 400ZR remains down.
The issue seems to have been introduced via https://github.com/sonic-net/sonic-platform-daemons/pull/400
The is_cmis_api API currently returns False for CCmis modules. Hence, the CMIS SM doesn't identify 400ZR and skips the port initialization as the desired application id is returned as None.
https://github.com/sonic-net/sonic-platform-daemons/blob/502c0b6622008363cb1ed6d1b7c85b4093997093/sonic-xcvrd/xcvrd/xcvrd.py#L134-L135
Link up on 400ZR has been verified after switch boot-up.
```
root@sonic:/home/admin# show int status Ethernet144
Interface                            Lanes    Speed    MTU    FEC         Alias    Vlan    Oper    Admin                                             Type    Asym PFC
----------- …
```

400ZR not linking up with latest SONiC master image

---

sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py

Currently, the CmisManagerTask thread crashes with the below traceback when subport interfaces are created.
```
E               Dec  4 06:47:53.773502 dut-sonic ERR pmon#xcvrd[197]: Exception occured at CmisManagerTask thread due to KeyError(None)
E               
E               Dec  4 06:47:53.777609 dut-sonic ERR pmon#xcvrd[197]: Traceback (most recent call last):
E               
E               Dec  4 06:47:53.777609 dut-sonic ERR pmon#xcvrd[197]:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1717, in run
E               
E               Dec  4 06:47:53.777724 dut-sonic ERR pmon#xcvrd[197]:     self.task_worker()
E               
E               Dec  4 06:47:53.777724 dut-sonic ERR pmon#xcvrd[197]:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", …
```

Mark sub-port interfaces as invalid ports in xcvrd

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Add 800G ifname in xcvrd get_interface_speed() which gets the port speed from the host interface name. 
Verified with enabling 800G module app code

Support 800G ifname in xcvrd

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/435/files
We are currently planning move the "active_firmware" and "inactive_firmware" fields from TRANSCEIVER_INFO table to TRANSCEIVER_FIRMWARE_INFO table.
MSFT ADO - 26788447
The changes in this PR should be merged along with https://github.com/sonic-net/sonic-platform-common/pull/440 and https://github.com/sonic-net/sonic-mgmt/pull/11708
Both active and inactive firmware version fields can dynamically change during firmware upgrade unlike other fields in TRANSCEIVER_INFO table which are static.
Hence, we are planning to create a separate table to store the firmware version so that these fields can be updated periodically by DomInfoTaskUpdate thread. A separate PR will be raised to enable polling of firmware …

[202305] Move firmware version fields to TRANSCEIVER_FIRMWARE_INFO table (#435)

---

sonic-xcvrd/xcvrd/xcvrd.py

A new cable was added to the list of supported CMIS modules
In xcvrd, within the CmisManagerTask thread, there is a list of supported CMIS modules. The CMIS state machine only
starts for modules found in this list. Currently, a certain type of CMIS module, OSFP-8X, is missing from this list. Hence, the
configuration for such modules will be skipped by the CmisManagerTask.
Without this change, xcvrd wouldn't be able to configure OSFP-8X modules.
I confirmed that when an OSFP-8X module is plugged in, the CMIS state machine is triggered, and the module SI
parameters are retrieved from optics_si_settings.json and configured successfully.

Update for supported CMIS module types in xcvrd to include a new module: OSFP-8X

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/443
---------
MSFT ADO - 26801871
We need to enable periodic update of TRANSCEIVER_FIRMWARE_INFO table so that the active_firmware and inactive_firmware fields are periodically updated in the redis-db. Periodic polling of firmware version will enable XCVRD to update firmware version for all breakout ports of a physical port after performing firmware upgrade using any one of the breakout port.
Also, a new CLI (`config interface transceiver dom PORT_NAME enable/disable`) has been created to allow user enable/disable DOM monitoring. XCVRD needs to handle this CLI so that periodic polling through DomInfoUpdateTask thread is enabled/disabled for a particular port.
The new CLI will set `dom_polling` field in …

[202305] Enable periodic polling of TRANSCEIVER_FIRMWARE_INFO table in DomInfoUpdateTask

---

sonic-sensormond/scripts/sensormond
sonic-sensormond/tests/sensors.yaml
sonic-sensormond/tests/test_sensormond.py

Added support for file systems based sensors implementation in Sensormond. 
See HLD for reference.
Provides an easy way to add support for different vendor platforms in Sensormond.
Unit Test and target test.

Added support for file system based sensors implementation.

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

We currently need to disable periodic DOM polling of a port through DomInfoUpdateTask thread during CMIS initialization.
Disabling of DOM polling during CMIS initialization is primarily needed to disable sending CDB commands to read FW version from DomInfoUpdateTask thread during CMIS initialization.
For transceivers which do not support CDB background mode, any EEPROM access to the module can fail if a CDB command is executed at the same time.
In order to disable DOM polling during CMIS initialization, the `cmis_state` from CmisManagerTask thread is now being updated in the `TRANSCEIVER_STATUS` table of STATE_DB.
If the current `cmis_state` does not belong to `CMIS_TERMINAL_STATES`, DomInfoUpdateTask will disable DOM polling for the port to allow CmisManagerTask thread to complete CMIS …

Disable periodic polling of port in DomInfoUpdateTask thread during CMIS init

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/449
We currently need to disable periodic DOM polling of a port through DomInfoUpdateTask thread during CMIS initialization.
Disabling of DOM polling during CMIS initialization is primarily needed to disable sending CDB commands to read FW version from DomInfoUpdateTask thread during CMIS initialization.
For transceivers which do not support CDB background mode, any EEPROM access to the module can fail if a CDB command is executed at the same time.
In order to disable DOM polling during CMIS initialization, the `cmis_state` from CmisManagerTask thread is now being updated in the `TRANSCEIVER_STATUS` table of STATE_DB.
If the current `cmis_state` does not belong to `CMIS_TERMINAL_STATES`, DomInfoUpdateTask will …

[202305] Disable periodic polling of port in DomInfoUpdateTask thread during CMIS init

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/449
We currently need to disable periodic DOM polling of a port through DomInfoUpdateTask thread during CMIS initialization.
Disabling of DOM polling during CMIS initialization is primarily needed to disable sending CDB commands to read FW version from DomInfoUpdateTask thread during CMIS initialization.
For transceivers which do not support CDB background mode, any EEPROM access to the module can fail if a CDB command is executed at the same time.
In order to disable DOM polling during CMIS initialization, the `cmis_state` from CmisManagerTask thread is now being updated in the `TRANSCEIVER_STATUS` table of STATE_DB.
If the current `cmis_state` does not belong to `CMIS_TERMINAL_STATES`, DomInfoUpdateTask will …

[202311] Disable periodic polling of port in DomInfoUpdateTask thread during CMIS init

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Save TRANSCEIVER_INFO/STATUS tables on warm/fast-reboot.
The information in TRANSCEIVER_INFO tables is required for orchagent to set SAI_PORT_ATTR_HOST_TX_SIGNAL_ENABLE=true on system startup, otherwise after APPLY_VIEW port becomes down until pmon populates TRANSCEIEVER_INFO table.
Run fast/warm-reboot.

[warm/fast-reboot] Retain TRANSCEIVER_INFO/STATUS tables on deinit

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

backport https://github.com/sonic-net/sonic-platform-daemons/pull/456
Support to get the media_settings.json and optics_si_settings.json files from both the platform folder and the SKU folder.
It will search the HWSKU folder first and then fall back to the platform folder.
combine with PR https://github.com/sonic-net/sonic-buildimage/pull/18441, the vendor will be able to enable CMIS cable host mgmt. function per SKU(choose to put the specific pmon_daemon_control.json, media_settings.json and optics_si_settings.json to the SKU folder).
The vendor will have the flexibility to have both files in the platform scope or the SKU scope.
Build image, manually test,
1. put files in the platform folder, the settings should be able to be loaded.
2. put files in the SKU folder, the settings should be …

[202311] Support to get MEDIA_SETTING and OPTICS_SI from both platform folder and HWSKU folder

---

sonic-xcvrd/tests/test_xcvrd.py

An intermittent build failure is seen for the test_SfpStateUpdateTask_task_run_stop unit-test with the below backtrace. We have observed more than one type of backtrace so far (details are mentioned in the issues mentioned below).
```
[2023-06-21T12:27:31.213Z] =================================== FAILURES ===================================
[2023-06-21T12:27:31.213Z] ____________ TestXcvrdScript.test_SfpStateUpdateTask_task_run_stop _____________
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] self = <tests.test_xcvrd.TestXcvrdScript object at 0x7ff1f404b610>
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] @patch('xcvrd.xcvrd_utilities.port_mapping.subscribe_port_config_change', MagicMock(return_value=(None, None)))
[2023-06-21T12:27:31.213Z] def …
```

Fix intermittent build failure for test_SfpStateUpdateTask_task_run_stop

---

sonic-xcvrd/tests/test_xcvrd.py

Cherry-pick for #461 
MSFT ADO - 24271303
An intermittent build failure is seen for the test_SfpStateUpdateTask_task_run_stop unit-test with the below backtrace. We have observed more than one type of backtrace so far (details are mentioned in the issues mentioned below).
```
[2023-06-21T12:27:31.213Z] =================================== FAILURES ===================================
[2023-06-21T12:27:31.213Z] ____________ TestXcvrdScript.test_SfpStateUpdateTask_task_run_stop _____________
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] self = <tests.test_xcvrd.TestXcvrdScript object at 0x7ff1f404b610>
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] @patch('xcvrd.xcvrd_utilities.port_mapping.subscribe_port_config_change', MagicMock(return_value=(None, None))) …
```

[202311] Fix intermittent build failure for test_SfpStateUpdateTask_task_run_stop

---

sonic-xcvrd/tests/test_xcvrd.py

Cherry-pick for #461 
MSFT ADO - 24271303
An intermittent build failure is seen for the test_SfpStateUpdateTask_task_run_stop unit-test with the below backtrace. We have observed more than one type of backtrace so far (details are mentioned in the issues mentioned below).
```
[2023-06-21T12:27:31.213Z] =================================== FAILURES ===================================
[2023-06-21T12:27:31.213Z] ____________ TestXcvrdScript.test_SfpStateUpdateTask_task_run_stop _____________
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] self = <tests.test_xcvrd.TestXcvrdScript object at 0x7ff1f404b610>
[2023-06-21T12:27:31.213Z]
[2023-06-21T12:27:31.213Z] @patch('xcvrd.xcvrd_utilities.port_mapping.subscribe_port_config_change', MagicMock(return_value=(None, None))) …
```

[202305] Fix intermittent build failure for test_SfpStateUpdateTask_task_run_stop

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/port_event_helper.py

Ignore processing the front panel ports in xcvrd. This include ports with suffixes other than Ethernet<num> and ports that have role field set to any value other than Ext. 
Requires: https://github.com/sonic-net/sonic-buildimage/pull/18465

[xcvrd] Ignore processing ports that are not front-panel

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

Support to get the media_settings.json and optics_si_settings.json files from both the platform folder and the SKU folder.
It will search the HWSKU folder first and then fall back to the platform folder.
combine with PR https://github.com/sonic-net/sonic-buildimage/pull/18441, the vendor will be able to enable CMIS cable host mgmt. function per SKU(choose to put the specific pmon_daemon_control.json, media_settings.json and optics_si_settings.json to the SKU folder).
The vendor will have the flexibility to have both files in the platform scope or the SKU scope.
Build image, manually test,
1. put files in the platform folder, the settings should be able to be loaded.
2. put files in the SKU folder, the settings should be able to be loaded.
3. put the files in both platform and SKU folder, …

Support to get MEDIA_SETTING and OPTICS_SI from both platform folder and HWSKU folder

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

The current implementation in chassisd has NO method to differentiates a module (Linecard & Farbic card) slot is empty during boot up or module is reseatted or removal.  Add get_module_current_status() to fetch the previous status from DB. And compare it to the new status to log a proper message.
After this change, the following is behaviours:
1) No longer log "Module LINE-CARD5 went off-line!" for empty slot upon Supervisor reboot 
2) There be any LINECARD Chassis db cleanup happened after the 30 minutes timeout
3) The following messages will be logged for a Linecard which is online upon Supervisor reboot 
```
Apr  9 19:05:43.028168 ixre-cpm-chassis15 NOTICE pmon#chassisd: Module SUPERVISOR0 is on-line!
Apr  9 19:05:43.233794 ixre-cpm-chassis15 NOTICE pmon#chassisd: Module LINE-CARD0 is …
```

[chassis][linecard] Fix Module LINECARD<> went off-line message for empty slot issue

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/18468
xcvrd crashes due to PR https://github.com/sonic-net/sonic-platform-common/pull/397.
Insert CMIS DAC cable 
```
root@sonic:/tmp# show interfaces transceiver eeprom Ethernet256 -d
Ethernet256: SFP EEPROM detected
Active Firmware: N/A
Active application selected code assigned to host lane 1: N/A
Active application selected code assigned to host lane 2: N/A
Active application selected code assigned to host lane 3: N/A
Active application selected code assigned to host lane 4: N/A
Active application selected code assigned to host lane 5: N/A
Active application selected code assigned to host lane 6: N/A
Active application selected code assigned to host lane 7: N/A
Active application selected code assigned to host lane 8: N/A …
```

[Xcvrd] Skip to get dom/threshold/pm for flat memory

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Configuring frequency for ZR optics , which is not a multiple of 75Ghz was throwing exception causing xcvrd to crash.
Added validation check for 75GHz Grid without throwing exception and returning false/true value based on the input.
This change currently supports only 75GHz grid value and not any other frequency.
root@sonic:/home/cisco# sudo config interface -n asic2 transceiver frequency Ethernet200 196000
Setting laser frequency to 196000 GHz on port Ethernet200
root@sonic:/home/cisco#
Cause xcvrd to crash
Configured frequency which was within the min and max supported limits with 2 sample size
1. Multiple of Grid frequency (75Ghz). Expectation is laser frequency configuration should be successful.
2. Not a multiple of Grid Frequency. Xcvrd should not crash
CONFIGURED 191450 WHICH IS …

Adding frequency grid validation for ZR optics 

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Save TRANSCEIVER_INFO/STATUS tables on warm/fast-reboot.
The information in TRANSCEIVER_INFO/STATUS tables is required for orchagent to set SAI_PORT_ATTR_HOST_TX_SIGNAL_ENABLE=true on system startup.
Run fast/warm-reboot.

[202311][warm/fast-reboot] Retain TRANSCEIVER_INFO/STATUS tables on deinit

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Currently, the CmisManagerTask thread crashes upon encountering an exception which causes the entire XCVRD process to restart. The CmisManagerTask thread crash scenarios are more often seen during instances of failure to read EEPROM of the transceivers.
Crash snippet
```
Apr  1 13:39:29.652330 STG01-0101-0200-02T2-lc01 ERR pmon#: Exception occured at CmisManagerTask thread due to TypeError("'NoneType' object is not subscriptable")
Apr  1 13:39:29.654469 STG01-0101-0200-02T2-lc01 ERR pmon#: Traceback (most recent call last):
Apr  1 13:39:29.654498 STG01-0101-0200-02T2-lc01 ERR pmon#:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1693, in run
Apr  1 13:39:29.654498 STG01-0101-0200-02T2-lc01 ERR pmon#:     self.task_worker()
Apr  1 13:39:29.654498 …
```

Handling exceptions in CMIS SM to prevent xcvrd crash

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

Fix issue: logical_port_name is not defined
Fix issue: logical_port_name is not defined
Manual test

[xcvrd] Fix issue: logical_port_name is not defined

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

202311 cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/483
Currently, the CmisManagerTask thread crashes upon encountering an exception which causes the entire XCVRD process to restart. The CmisManagerTask thread crash scenarios are more often seen during instances of failure to read EEPROM of the transceivers.
Crash snippet
```
Apr  1 13:39:29.652330 STG01-0101-0200-02T2-lc01 ERR pmon#: Exception occured at CmisManagerTask thread due to TypeError("'NoneType' object is not subscriptable")
Apr  1 13:39:29.654469 STG01-0101-0200-02T2-lc01 ERR pmon#: Traceback (most recent call last):
Apr  1 13:39:29.654498 STG01-0101-0200-02T2-lc01 ERR pmon#:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1693, in run
Apr  1 13:39:29.654498 …
```

[202311] Handling exceptions in CMIS SM to prevent xcvrd crash

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

202305 cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/483
Currently, the CmisManagerTask thread crashes upon encountering an exception which causes the entire XCVRD process to restart. The CmisManagerTask thread crash scenarios are more often seen during instances of failure to read EEPROM of the transceivers.
Crash snippet
```
Apr  1 13:39:29.652330 STG01-0101-0200-02T2-lc01 ERR pmon#: Exception occured at CmisManagerTask thread due to TypeError("'NoneType' object is not subscriptable")
Apr  1 13:39:29.654469 STG01-0101-0200-02T2-lc01 ERR pmon#: Traceback (most recent call last):
Apr  1 13:39:29.654498 STG01-0101-0200-02T2-lc01 ERR pmon#:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1693, in run
Apr  1 13:39:29.654498 …
```

[202305] Handling exceptions in CMIS SM to prevent xcvrd crash

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Modified the SUP chassisd check_midplane_reachability() function to use the CHASSIS_MODULE_REBOOT_INFO_TABLE data (which is set by Linecard "sudo reboot" command)  log expected or unexpected  module lost midplane connectivity.  This address issue  https://github.com/sonic-net/sonic-buildimage/issues/18540
Add a new method is_module_reboot_expected() to check if CHASSIS_MODULE_REBOOT_INFO_TABLE|LINECARD# entry exists in CHASSIS_STATE_DB when a linecard is not reachable from SUP.  If entry exists, it is expected reboot.  check_midplane_reachability() will log  "pmon#chassisd: Expected: Module LINE-CARD1 lost midplane connectivity".  If entry doesn't exist, it will log "pmon#chassisd: Unexpected: Module LINE-CARD1 lost midplane connectivity".  The  CHASSIS_MODULE_REBOOT_INFO_TABLE|LINECARD# …

[chassis][midplane] Modify the chassisd to log expected/unexpected midplane connectivity messages

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

CMIS 'ConfigSuccess" failure while changing default ApSel code for 800G DR8/FR8 modules
Issue seen with vendors:
Eoptolink
Finisar
Source-Photonics
Ex: If module supports 800G, 400G and 100G app code and has default app mode as 800G, an issue has arisen with the 2x400G target mode which is hitting ConfigRejectedPartailDataPath error and failing. (same as 8x100 App mode)
Extract from CMIS spec: - 6.2.4.3 Host Rules and Recommendations
```The host can change the width of a Data Path only while in the DPDeactivated state, i.e. the host must always transition an existing Data Path to DPDeactivated before selecting an Application with a different lane count. Any lane that becomes unused must be marked as such (AppSel = 0000b) or it must be assigned to a new valid Data Path (remaining in …
```

CMIS 'ConfigSuccess" failure while changing default ApSel code for 800G DR8/FR8 modules

---

sonic-chassisd/scripts/chassisd

For the Nokia SONiC chassis procedures for insertion/hot swap of Switch Fabric Module(SFM), 
the previous solution was using the below commands.
```
sudo nokia_cmd set shutdown-sfm <SFM-Num/Physical-Slot>
```
The below 4 PRs intend to add the below commands for the equivalent operations.
https://github.com/sonic-net/sonic-platform-daemons/pull/491
https://github.com/sonic-net/sonic-utilities/pull/3283
https://github.com/nokia/sonic-platform/pull/6
https://github.com/sonic-net/sonic-buildimage/pull/18938
```
sudo config chassis modules shutdown/startup <module name>
```
The HLD for Shutdown and Startup of the Fabric Module is below:
https://github.com/sonic-net/SONiC/pull/1694
The below PR was replaced.
https://github.com/sonic-net/sonic-buildimage/pull/18578
- Microsoft ADO **(number …

Update for the procedures for insertion/hot swap of Switch Fabric Module (SFM) by using "config chassis modules shutdown/startup" commands

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix for https://github.com/sonic-net/sonic-buildimage/issues/19116 [xcvrd] typo "log_notifce" results in port oper down

Fix for #19116 [xcvrd] typo "log_notifce" results in port oper down

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Skip the re-init flow for the SW-controlled ports in case of fastboot.
Because during fastboot the switch didn't reset the modules, so there is no need to reinitialize them.
To improve the fastboot data-plane disruption time.
Run the [sonic-mgmt/tests/platform_tests/test_advanced_reboot.py::test_fast_reboot](https://github.com/sonic-net/sonic-mgmt/blob/de7ad768f74efb04301dccbfa004a5a109b84c91/tests/platform_tests/test_advanced_reboot.py#L62)

[CMIS] Skip re-init flow for SW-controlled ports in case of fastboot

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Backport of https://github.com/sonic-net/sonic-platform-daemons/pull/497
Skip the re-init flow for the SW-controlled ports in case of fastboot.
Because during fastboot the switch didn't reset the modules, so there is no need to reinitialize them.
To improve the fastboot data-plane disruption time.
Run the [sonic-mgmt/tests/platform_tests/test_advanced_reboot.py::test_fast_reboot](https://github.com/sonic-net/sonic-mgmt/blob/de7ad768f74efb04301dccbfa004a5a109b84c91/tests/platform_tests/test_advanced_reboot.py#L62)

[202311][CMIS] Skip re-init flow for SW-controlled ports in case of fastboot

---

sonic-xcvrd/xcvrd/xcvrd.py

In function `get_interface_speed`, it will log an error if the application name does not contain a valid speed. However, many modules support both ethernet and non-ethernet (e.g. IB) application, non-ethernet application would not contain a valid speed. For such module, the function `get_interface_speed` logs an error to syslog:
```
Jun 12 20:09:57.315556 sonic ERR pmon#xcvrd: No interface speed found for: 'IB HDR (Arch.Spec.Vol.2)'
``` 
Actually, this is not an error because the module will finally find a proper application via the for loop in function `get_cmis_application_desired`
Remove the unexpected error log since it could be a false alarm. Also, log the module applications if it cannot find a proper application.
Manual test

[xcvrd] Fix issue: do not print error log when module support non-ethernet application

---

sonic-xcvrd/xcvrd/xcvrd.py

Change log level to notice and add more information when application is not found for a module.
In existing setups, there might be ports that were set to admin down. Those ports may not have correct speed configuration which would cause error logs when applying media settings:
```
Jun 17 20:27:58.041567 sonic ERR pmon#xcvrd: Failed to get desired application from {1: {'host_electrical_interface_id': 'IB HDR (Arch.Spec.Vol.2)', 'module_media_interface_id': 'Copper cable', 'media_lane_count': 4, 'host_lane_count': 4, 'host_lane_assignment_options': 17}, 2: {'host_electrical_interface_id': 'IB SDR (Arch.Spec.Vol.2)', 'module_media_interface_id': 'Copper cable', 'media_lane_count': 4, 'host_lane_count': 4, 'host_lane_assignment_options': 17}, 3: {'host_electrical_interface_id': '200GBASE-CR4 …
```

[xcvrd] change log content and log level when application is not found

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py

Let media_settings.json can use regular expression to match 'vendor key' or 'media key'
when define a set of transceiver to use the same SI value.
Make the definition of SI value for a set of vendor or media can be more flexible
`root@sonic:~# cat /var/log/swss/swss.rec | grep preemphasis`
`2024-04-17.01:53:10.594465|PORT_TABLE:Ethernet0|SET|preemphasis:0x0c8418,0x0c8418,0x0c8418,0x0c8418`
`2024-04-17.01:53:11.827324|PORT_TABLE:Ethernet4|SET|preemphasis:0x0c8418,0x0c8418,0x0c8418,0x0c8418`
Example of media_settings.json
`    "GLOBAL_MEDIA_SETTINGS": {`
`        "1-32": {`
`            "VENDOR.*-PN.*": {`
`                "preemphasis": {`
`                    "lane0": "0x0c8418",`
`                    "lane1": "0x0c8418",`
`                    "lane2": "0x0c8418",`
` …

[xcvrd] Modify to support regular expression when parsing the key in media_settings.json

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

For a given logical port, CmisManagerTask thread updates the application specific fields in TRANSCEIVER_INFO table only for the relevant active lanes for a given subport.
However, the "show interfaces transceiver eeprom PORT_NAME" CLI shows data for all the 8 lanes and not just the active lanes for the given logical port. However, the data of non-active lanes is incorrect. This needs to be corrected.
In the below example, logical ports Ethernet16 through Ethernet22 are subports 1 through subport 4 respectively. Each logical ports has different values of "Active application selected code assigned to host lane" for their corresponding non-active lanes (the corresponding active lanes are populated correctly).
```
admin@th5-sw3:~$ show int trans eeprom -d Ethernet16 | grep code
Active …
```

Initialize application specific fields as 'N/A' in TRANSCEIVER_INFO table

---

sonic-ycabled/tests/test_y_cable_helper.py
sonic-ycabled/ycable/ycable.py
sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py
sonic-ycabled/ycable/ycable_utilities/y_cable_table_helper.py

This PR Introduces a an initialization mechanism within the wait_for_state_change function to ensure that the YcableChannelStateTableHelper instance is created only once per port.
Also it Adds a check using hasattr to see if table_helper is already an attribute of wait_for_state_change.
YcableChannelStateTableHelper instances are  keyed by port.
This helps ensure that channel object will have a seperate instance of swsscommon table and they will not interfere with normal functioning of state specific threads. 
```
28724244
```
UTs and deploying changes on Libra Testbeds as well as pilot devices
This script was used to test and after each run the output was matched to be as expected. 
The fwd_state table is continuously written when link goes down and comes up
`unknown` and `active` …

[ycabled][active-active] Fix in gRPC channel callback logic by creating swsscommon table within the context

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix https://github.com/sonic-net/sonic-buildimage/issues/19427

[xcvrd] Fix SfpStateUpdateTask crash for RJ45 cable type

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

During XCVRD boot-up, following messages are seen
```
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: STATE_DB
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: message repeated 3 times: [ :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: STATE_DB]
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: APPL_DB
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: :- ~RedisPipeline: RedisPipeline dtor …
```

Remove redundant xcvr_table_helper init during CmisManagerTask init

---

sonic-xcvrd/xcvrd/xcvrd.py

Backport https://github.com/sonic-net/sonic-platform-daemons/pull/503
Change log level to notice and add more information when application is not found for a module.
In existing setups, there might be ports that were set to admin down. Those ports may not have correct speed configuration which would cause error logs when applying media settings:
```
Jun 17 20:27:58.041567 sonic ERR pmon#xcvrd: Failed to get desired application from {1: {'host_electrical_interface_id': 'IB HDR (Arch.Spec.Vol.2)', 'module_media_interface_id': 'Copper cable', 'media_lane_count': 4, 'host_lane_count': 4, 'host_lane_assignment_options': 17}, 2: {'host_electrical_interface_id': 'IB SDR (Arch.Spec.Vol.2)', 'module_media_interface_id': 'Copper cable', 'media_lane_count': 4, 'host_lane_count': 4, …
```

[202405] [xcvrd] change log content and log level when application is not found

---

sonic-chassisd/scripts/chassisd

Per MSFT request, we enhance the module on-line and off-line messages with physical slot number
Before enhance:
pmon#chassisd: Module LINE-CARD0 is on-line!
pmon#chassisd: Module LINE-CARD0  went off-line!
pmon#chassisd: Module LINE-CARD0 recovered on-line!
pmon#chassisd: Module FABRIC-CARD6 is on-line!
After Enhance:
pmon#chassisd: Module LINE-CARD0 (Slot 1) is on-line!
pmon#chassisd: Module LINE-CARD0 (Slot 1) went off-line!
pmon#chassisd: Module LINE-CARD0 (Slot 1) recovered on-line!
pmon#chassisd: Module FABRIC-CARD6 (Slot 7) is on-line!
This change is required by 202205 branch also.
Per MSFT's request -- In order to easily identify a module within a chassis, we need to report the physical slot number whenever we raised “module” related syslogs.
Tested with Master branch and 202205 …

[chassis][pmon][chassid] Enhance the chassid module on-line or off-line log messages with physical slot number

---

sonic-xcvrd/xcvrd/xcvrd.py

Backport https://github.com/sonic-net/sonic-platform-daemons/pull/501
In function `get_interface_speed`, it will log an error if the application name does not contain a valid speed. However, many modules support both ethernet and non-ethernet (e.g. IB) application, non-ethernet application would not contain a valid speed. For such module, the function `get_interface_speed` logs an error to syslog:
```
Jun 12 20:09:57.315556 sonic ERR pmon#xcvrd: No interface speed found for: 'IB HDR (Arch.Spec.Vol.2)'
``` 
Actually, this is not an error because the module will finally find a proper application via the for loop in function `get_cmis_application_desired`
Remove the unexpected error log since it could be a false alarm. Also, log the module applications if it cannot find a proper application. …

[202405] [xcvrd] Fix issue: do not print error log when module support non-ethernet application

---

sonic-psud/scripts/psud
sonic-psud/tests/test_PsuChassisInfo.py

In psud script, first_run is always true in PsuChassisInfo class. This causes the method update_master_status() always set the psu status_master_led and log the status change messages although the status is not changed. The same NOTICE message is repeated and never stop.  Address this issue, added code to set the first_run to False after the first run.  This initializes set_led to False before the calculation.  So that it won't be True to trigger the set_status_maste_led() and log the same message while the status has NO change.
This PR fixes https://github.com/sonic-net/sonic-buildimage/issues/19780 and not set the LED to the same state or log the same message when there is NO change. 
Checking the syslog on the SUP.  The following message will not be repeated if the status is not …

[PMON][psud] Fix the repeated NOTICE log message on Chassis platform

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

202305 Cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/521
During XCVRD boot-up, following messages are seen
```
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: STATE_DB
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: message repeated 3 times: [ :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: STATE_DB]
/var/log/syslog.95.gz:Jun 28 09:59:05.175489 svcstr-7050-acs-2 NOTICE pmon#xcvrd[30]: :- ~RedisPipeline: RedisPipeline dtor is called from another thread, possibly due to exit(), Database: APPL_DB
/var/log/syslog.95.gz:Jun 28 …
```

[202305] Remove redundant xcvr_table_helper init during CmisManagerTask init

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Following logs are planned to be added to xcvrd for enhancing debuggability
1. Dumping Module and DataPath state during CMIS SM transition
2. Print a NOTICE if module is not CMIS
https://github.com/sonic-net/sonic-platform-daemons/blob/f581c06cd8adeb4b82816ee0fc38fd07b3f9e692/sonic-xcvrd/xcvrd/xcvrd.py#L1382
3. Add a NOTICE if sfp is not present while updating TRANSCEIVER_INFO table during SFP insertion
https://github.com/sonic-net/sonic-platform-daemons/blob/f581c06cd8adeb4b82816ee0fc38fd07b3f9e692/sonic-xcvrd/xcvrd/xcvrd.py#L442-L443
```
Log for #1
2024 Sep 18 21:37:02.573152 sonic NOTICE pmon#xcvrd: CMIS: Ethernet0: 400G, lanemask=0xff, CMIS state=INSERTED, Module state=ModuleReady, DP state={'DP1State': 'DataPathActivated', 'DP2State': 'DataPathActivated', 'DP3State': …
```

[xcvrd] Add logs to improve debugging in xcvrd

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py

Enhance/fix media_settings infra in below aspects:
1. Support/fix for 100G QSFP28 transceivers:
- fix its issue of `media_key` parsed as `QSFP28-Unknown-...` due to its compliance code defined in [`Extended Specification Compliance`](https://github.com/sonic-net/sonic-platform-common/blob/7f07fa68eff8954cbd36400d39fd6f3d81b9a850/sonic_platform_base/sonic_xcvr/codes/public/sff8024.py#L114-L175) field rather than `10/40G Ethernet Compliance Code`
```
Example transceiver info for 100G QSFP28:
root@sonic:/home/cisco# show int trans info Ethernet176
Ethernet176: SFP EEPROM detected
Application Advertisement: N/A
...
Identifier: QSFP28 or later
...
Specification compliance:
10/40G Ethernet Compliance Code: Unknown
Extended Specification Compliance: 100GBASE-CR4, 25GBASE-CR CA-25G-L or …
```

Improve parsing of media-settings.json for non-CMIS and breakout ports

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
sonic-xcvrd/xcvrd/xcvrd_utilities/xcvr_table_helper.py

Ensure Xcvrd crash and restart should be handled gracefully on platforms that need custom SI settings.
The goal is to avoid link flap on platforms that need custom SI settings during xcvrd restart.
**Changeset 1**
The changeset is partial implementation of the changes required for https://github.com/sonic-net/SONiC/pull/1432/.
Specifically, the current change adds `NPU_SI_SETTINGS_SYNC_STATUS` key to the PORT_TABLE of STATE_DB. Following is the usage of `NPU_SI_SETTINGS_SYNC_STATUS` key
Value | Modifier thread and event | Consumer thread and purpose
-- | -- | --
NPU_SI_SETTINGS_DEFAULT | 1.   XCVRD main thread during cold start of XCVRD   2. SfpStateUpdateTask during transceiver removal | XCVRD   main thread during boot-up for deciding to notify NPU SI settings
NPU_SI_SETTINGS_NOTIFIED | …

Xcvrd crash and restart should not cause link flap on platforms needing custom NPU SI settings

---

sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py

Removed the lane_speed key construction failure log from media_settings_parser.
The lane_speed_key is one of the key types used for the media_settings.json lookup.
This type of key is not relevant for all vendors, and thus it is not mandatory.
After some discussion, it was decided to completely remove this error log.

Reduce log level for lane speed key construction failure

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/dom_mgr.py
sonic-xcvrd/xcvrd/xcvrd.py

We need to move the DomInfoUpdateTask class to a separate file to improve modularity and for better code maintainability.
https://github.com/sonic-net/sonic-platform-daemons/blob/ca812b0df105ecb98b90f2b9ef6b7aa24592222b/sonic-xcvrd/xcvrd/xcvrd.py#L1684
MSFT ADO - 29932076
Following is the summary of the changes done in this PR
1. Added `DOM-INFO-UPDATE:` keyword to all syslogs being logged by the DomInfoUpdateTask class.
2. Moved the below functions related to DB update from xcvrd.py to dom_mgr.py
a. post_port_sfp_firmware_info_to_db
b. post_port_dom_info_to_db
c. update_port_transceiver_status_table_hw
d. post_port_pm_info_to_db
3. Consolidated beautify_transceiver_status_dict and beautify_pm_info_dict functions into beautify_info_dict function to avoid code duplication. This was done in …

Move DomInfoUpdateTask class to a separate file

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py
sonic-chassisd/tests/test_dpu_chassisd.py

Implement the Chassis daemon that runs on the Smart Switch DPU is responsible for maintaining the DPU state in the `CHASSIS_STATE_DB`. DB schema is defined in [Smart Switch PMON HLD](doc/smart-switch/pmon/smartswitch-pmon.md).
Provide up-to-date DPU data and control plane states in the CHASSIS_STATE_DB.
The new functionality is fully covered with the UT provided in this PR.

[SmartSwitch] Add implementation for the DPU chassis daemon.

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

Depends on https://github.com/sonic-net/sonic-buildimage/pull/19611
Use new logger class `SysLogger` and enable runtime log level configuration
Use new logger class `SysLogger` and enable runtime log level configuration
Manual test

[xcvrd] Use new logger implementation and enable runtime log level configuration

---

sonic-chassisd/scripts/chassisd

During chassis reboot,  PMON on the LC could be in the middle of running module_db_update() which may try to access the CHASSIS_STATE_DB on the SUP to get the ASIC info.  If the ASIC table info on SUP has been removed due to reboot, the dictionary could be empty. Directly check its value could cause KeyErr.  This PR add code to checks if key exists before using its value.  Fixes https://github.com/sonic-net/sonic-buildimage/issues/20543
This is timing related issue in the chassis setup.  Per discussion, we should always check if the key exists in the dictionary. This PR add code to check if the key CHASSIS_MODULE_INFO_NAME_FIELD is in fvs before checking its value.  This will avoid the traceback occurs.  Fixes https://github.com/sonic-net/sonic-buildimage/issues/20543
This is needed by …

[chassis][pmon] Fix the PMON traceback issue while chassis is rebooting

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_dpu_chassisd.py

Extend the DPU chassis daemon to support subscriptions to data planes and control plane state changes.
This allows the optimization of CPU usage and removes the delay in state change processing compared to polling.
New unit tests were added to cover new functionality.

[SmartSwitch] Extend implementation of the DPU chassis daemon.

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

Enabled `thermalctld` to run on DPU chassis to update data to `CHASSIS_STATE_DB` based on dpu_id
`thermalctld` is required to update the TEMPERATURE_INFO table to `CHASSIS_STATE_DB` as the data has to be proccessed by the switch in order to handle thermal algorithms at the switch side

[Smartswitch][DPU] Addition of DPU Chassis for thermalctld

---

sonic-stormond/scripts/stormond
sonic-stormond/tests/test_DaemonStorage.py

Currently the Storage monitoring Daemon does not provide any information on when it last synced attributes of each storage device onto the database. This PR adds new dynamic field called `last_sync_time` that shows when STORAGE_INFO fields for each disk was last synced to STATE_DB. The value is in Unix timestamp format.
HLD Change PR: https://github.com/sonic-net/SONiC/pull/1784
The motivation is that this field would provide additional context in case of repeated daemon crashes scenario ending up with the daemon status = `FATAL     Exited too quickly (process log may have details).`
Manually tested my changes on a DUT:
1. Let the daemon run for 10 minutes and then stopped it to sim a `FATAL` scenario:
2. Let some time pass: 
```
root@sonic-device:/usr/local/bin# date +%s
1724487680
``` …

[stormond] Added new dynamic field 'last_sync_time' to STATE_DB

---

sonic-chassisd/scripts/chassisd

When LC is absent for 30 minutes, the database cleanup kicks in.  When LagId is released, it needs to be appended to the SYSTEM_LAG_IDS_FREE_LIST
This PR works with the following 2 PRs:
https://github.com/sonic-net/sonic-swss/pull/3303
https://github.com/sonic-net/sonic-buildimage/pull/20369
Based on the dependency, the below order to merge these 3 PRs can help to avoid breaking the image run:
First:  PR https://github.com/sonic-net/sonic-buildimage/pull/20369
second: PR https://github.com/sonic-net/sonic-swss/pull/3303
Third: PR https://github.com/sonic-net/sonic-platform-daemons/pull/542 (This PR)
To address the issue of the same lagid could be used by two Portchannels in two different linecards. This issue occurs when reboot many Linecards together with 20 seconds delay in each LC …

[lag_id] Add lagid to free_list when LC absent for 30 minutes

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Fixed the bug in chassisd due to which incorrect number of ASICs were being pushed to CHASSIS_STATE_DB.
Fixes: [#559](https://github.com/sonic-net/sonic-platform-daemons/issues/559)
```
admin@cmp217:~$ sonic-db-cli CHASSIS_STATE_DB hgetall "CHASSIS_MODULE_TABLE|LINE-CARD4"
{'slot': '5', 'hostname': 'cmp217-5', 'num_asics': '2'}
```
Checked on `Arista 7804R3-FM ` platform with `Arista 7800R3A-36DM2-C36` linecard inserted which has 2 ASICs
Added a unit test for forwarding ASICs to test the same.

Fixed bug in chassisd causing incorrect number of ASICs in CHASSIS_STATE_DB

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/mock_platform.py
sonic-thermalctld/tests/test_thermalctld.py

This adds support to the `show platform fans` command to show fans that are on modules.
In the current Arista chassis model, the chassis fans are returned by `Module.get_all_fans()` as opposed to `FanDrawer.get_all_fans()`, which currently thermalctld makes no provision for. This change allows fans that are under the modules to be listed in the command output.
This has been tested internally on a chassis, and the fan output now includes all fans on the chassis as opposed to just PSU fans:
```
admin@cmp206:~$ show platform fan
Drawer    LED     FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ------  -------  -----------  ----------  --------  -----------------
N/A    off  fan0/1      29%      exhaust     Present        OK  20241030 15:54:08
N/A    off …
```

thermalctld: Add support for fans on non-CPU modules

---

sonic-xcvrd/xcvrd/sff_mgr.py

Fix non-CMIS transceivers in down state by bringing them out of low power mode in the SFF Manager Task.
This is intended to work together with the change in https://github.com/sonic-net/sonic-buildimage/pull/20886.
Non-CMIS transceivers were not functioning correctly when put into Low Power mode. So XCVRD now brings them out of lpmode.
Loaded an image containing this change alongside the change from https://github.com/sonic-net/sonic-buildimage/pull/20886 on an Arista chassis containing a Clearwater2 linecard.
Verified that without this image some interfaces were in a down state but with the image all interfaces came up as expected.

Take non-CMIS xcvrs out of lpmode in SFF Manager

---

sonic-psud/scripts/psud

Move the PSU parent information generation to the loop run function from the initialization function
Fixes https://github.com/sonic-net/sonic-platform-daemons/issues/575
Tested on Cisco chassis, the `PHYSICAL_ENTITY_INFO|PSU *` can be re-inserted after thermalctld restart.
And monitored the stated db for memory for hours, works well:
```
admin@x-sup-2:~$ date && sudo ip netns exec asic0 /usr/bin/redis-cli INFO memory
Mon Dec 16 12:54:24 AM UTC 2024
used_memory:3102440
used_memory_human:2.96M
used_memory_rss:19279872
used_memory_rss_human:18.39M
used_memory_peak:6644264
used_memory_peak_human:6.34M
used_memory_peak_perc:46.69%
used_memory_overhead:1595144
used_memory_startup:914032
used_memory_dataset:1507296
used_memory_dataset_perc:68.88%
allocator_allocated:3591336 …
```

[chassis][psud] Move the PSU parent information generation to the loop run function from the initialization function

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

On Nokia platform, slot name of Supervisor is string "A" instead of a number. Using "int" to convert it could cause issue backtrace.   We should use slot value to any checking without any conversion. This will fixes  https://github.com/sonic-net/sonic-buildimage/issues/21131
Modify the _get_module_info not to convert "slot" to a string value.  And also modify the code not to convert slot value to an to do any checking.  Just directly use the returned value of get_slot().  Also add UT  test_moduleupdater_check_slot_string() to valid it.
Tested on 202405 branch

[chassisd] Address the chassisd crash issue and add UT for it

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py
sonic-chassisd/tests/test_dpu_chassisd.py

Currently the time format being updated by the DPU and Switch are not aligned, this PR takes the common format from the HLD for all 3 states - midplane state, controlplane state and dataplane state
This also fixes the issue where the local time was represented incorrectly as UTC time
Current format:
```
Name    Oper-Status     State-Detail             State-Value    Time                             Reason
------  --------------  -----------------------  -------------  -------------------------------  --------
DPU0    Partial Online  dpu_midplane_link_state  up             Wed Jan 15 12:17:44 PM UTC 2025
dpu_control_plane_state  up             2024-11-25 04:32:45
dpu_data_plane_state     down           2024-11-25 04:32:45
```
After fix:
```
Name    Oper-Status     State-Detail …
```

[Smartswitch] Fix time format for dpu states

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

In the add_rack test, it would compare the TRANSCEIVER_INFO for two cases:
case 1. config reload (the admin status of Ethernet64 is down in config_db.json)
case 2. config reload (the admin status of Ethernet64 is up in config_db.json) and then shutdown Ethernet64
In case 1. it would not do CMIS init and the active application is 'N/A'.
In case 2. it would do CMIS init first and then disable TX. The active application would retain the value of the last CMIS init.
=> Modify the code to reset the active application on port shutdown to ensure that the active application would be the same for the above two cases.
```
root@ais800-64o-1:/# show interfaces status Ethernet0
Interface        Lanes    Speed    MTU    FEC          Alias    Vlan    Oper    Admin                           Type    Asym …
```

reset active application code as 'N/A' when port shutdown

---

sonic-chassisd/scripts/chassisd

Fix for dpu midplane state update affecting dpu control_plane/data_plane state
The dpu midplane update and the dpu cp/dp state update happen in parallel. The midplane state update function reads the data from redis-DB, udpates the midplane state and then writes back the entire table. It appears like the DPU cp/dp state update sometimes goes in between the midplane read and and write causing a wrong update of dpu cp/dp states. The fix is to avoid reading the table and just write only the dpu midplane state.  This will solve the problem.
The dpu midplane update and the dpu cp/dp state update happen in parallel. The midplane state update function reads the data from redis-DB, udpates the midplane state and then writes back the entire table. It appears like the DPU cp/dp state update …

Fix for dpu midplane state update affecting dpu control_plane/data_plane state :issue-21371

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

After sonic-mgmt tests, it does a config consistency check and if the config consistency check fails, it runs recover_chassis(). That function simultaneously runs config_reload on the supervisor and all linecards (in parallel). This means that the supervisor networking can be in the process of restarting when thermalctld exits and goes through the cleanup process of deleting entries from chassisdb.
This fixes a thermalctld crash when the supervisor and linecards simultaneously do a `config reload` (fixes sonic-net/sonic-buildimage#21058). This causes a failure during sonic-mgmt testing.
This change has been applied in Arista internal test environment and the thermalctl crash was not seen with this change applied.

thermalctld: Ignore exception when deleting chassisdb entry fails

---

sonic-xcvrd/xcvrd/xcvrd.py

For CMIS specific transceivers, read the key:value pairs directly from port_info_dict
Reduces duplication of the code and make it future ready for any new key:value pairs.
Verified 'show interfaces transceiver info' and 'sfputil show eeprom -p' outputs on an Arista testbed.

Refactor port_port_sfp_info_to_db() to read key:value pairs directly from port_info_dict

---

sonic-xcvrd/xcvrd/sff_mgr.py

Because the sff_mgr only brings ports out of low-power mode during xcvr insertion we see tests like `platform_tests/api/test_sfp.py::TestSfpApi::test_reset` fail.
`platform_tests/api/test_sfp.py::TestSfpApi::test_reset` does sfp_reset which puts the port back into low-power mode and then does a shut/no shut of the port expecting the port to come out of low-power mode.
With this change we'll now pull the port out of low-power mode on link up and `platform_tests/api/test_sfp.py::TestSfpApi::test_reset` will pass.
https://github.com/aristanetworks/sonic/issues/121

Have sff_mgr bring a linkup port out of lpmode

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Set the initial DPU admin state to "down" for DPUs that don't have the "CHASSIS_MODULE" configured.  The default is "down"
Fixes:  sonic-net/sonic-buildimage#21459
The chassisd config change handler is not triggering the config change event the very first time.
The new set of smartswitch tests added into sonic-mgmt

Fix for bug-21459: Set the initial DPU admin state

---

azure-pipelines.yml

Ensure that the pipeline fail to build if sonic-xcvrd whl package is missing __init__.py file.
- The `__init__.py` file is necessary in each directory to indicate that the directory should be treated as a package.
- Tools like `setuptools` and `find_packages()` rely on the presence of `__init__.py` files to identify packages and subpackages.
- Without `__init__.py` files, the directories will not be included in the package distribution, leading to incomplete or broken packages.
By ensuring that each directory contains an `__init__.py` file, we can create a complete and functional Python wheel package.
Pipeline:- https://dev.azure.com/mssonic/build/_build/results?buildId=800459&view=logs&j=6f26e4aa-3eaf-5d24-2c84-463275687676&t=9d0df2c7-e5fa-5a6f-3817-988ca77cdfbe

Add pipeline check for missing __init__.py in sonic-xcvrd whl package

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/dom/utilities/vdm/db_utils.py
sonic-xcvrd/xcvrd/xcvrd_utilities/utils.py

The following traceback is seen with the latest image for DAC cables.
```
2025 Mar 17 17:24:19.889826 sonic-dut ERR pmon#xcvrd[67]: Traceback (most recent call last):
2025 Mar 17 17:24:19.889997 sonic-dut WARNING pmon#xcvrd[67]: *** ('Ethernet259', 'STATE_DB', 'PORT_TABLE') handle_port_update_event() fvp {'host_tx_ready': 'false', 'index': '-1', 'port_name': 'Ethernet259', 'asic_id': 0, 'op': 'SET'}
2025 Mar 17 17:24:19.890132 sonic-dut ERR pmon#xcvrd[67]:   File "/usr/local/lib/python3.11/dist-packages/xcvrd/xcvrd.py", line 1878, in run
2025 Mar 17 17:24:19.890201 sonic-dut ERR pmon#xcvrd[67]:     self.task_worker(self.task_stopping_event, self.sfp_error_event)
2025 Mar 17 17:24:19.890397 sonic-dut WARNING pmon#xcvrd[67]: *** ('Ethernet21', 'STATE_DB', 'PORT_TABLE') …
```

[xcvrd] Skip VDM threshold DB update for flat memory transceivers

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

This commit fixes DPB support with CMIS transceivers.
CmisManagerTask's `port_dict` must be updated according to the port add/remove events.
This commit removes the `port_mapping` field from CmisManagerTask as
`port_mapping` was mostly used just for storing `asic_id` information
and that can be simply done by `port_dict` instead.
Added a helper method `get_asic_id()` method to CmisManagerTask for
getting `asic_id` from `logical_port`.
fixes https://github.com/sonic-net/sonic-buildimage/issues/18893
I tested on the VS environment.

[xcvrd] DPB support on platforms with CmisManagerTask enabled

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

XCVRD needs to wait for the MaxDurationDPTxTurnOff time after disabling Tx via the following API call:
https://github.com/sonic-net/sonic-platform-daemons/blob/f581c06cd8adeb4b82816ee0fc38fd07b3f9e692/sonic-xcvrd/xcvrd/xcvrd.py#L1468
This waiting period is essential to allow the module to transition to the DataPathInitialized state after disabling Tx. Failing to wait for the DataPathInitialized state may cause the module to behave unexpectedly, especially if Tx is disabled during CMIS initialization.
One possible way to run into port permanently having Tx disabled is during boot-up
In one case, following steps led to the Tx being disabled permanently on a module during switch boot-up
- OA sets host_tx_ready to False (06:48:48.670346)
- CMIS SM transitions to DP_TXON state …

[xcvrd] Add wait based on MaxDurationDPTxTurnOff after disabling Tx

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py

This change searches for a third generic key that covers medium type + lane speed. This will cover all Arista usecases as at Arista out tuning values are based off medium type + lane speed. Of course this will work for all vendors if they choose to do so. The consequence of this is that on bringup Arista can upload a single media_settings.json which will cover every possible speed and lane combination. Any users of our SKUs will not need to ever ask for updates to cover new optics, speeds etc.
Note if there is no xcvr present we will assume copper; this will cover internal phy to external phy connection, as well as any backplane links.
The new flow will look like: (Addition to current flow in green)
The current implementation of the the dynamic media tuning feature requires that you know …

Add third generic media tuning key to search for (medium+lane)

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_platform.py
sonic-chassisd/tests/test_chassisd.py
sonic-thermalctld/scripts/thermalctld

1. Add Fabric Card Module information to STATE_DB. This information
is necessary as in the tests we expect for fans under fabric cards,
their parent information (i.e fabric cards) is also present in the
`PHYSICAL_ENTITY_INFO` of `STATE_DB`.
2. Rather than storing a module by its index, store it by its name.
This makes it easier to refer to modules as sometimes index/position
of module may change, but it's name remains consistent.
This was done as part of changes to fix https://github.com/sonic-net/sonic-mgmt/issues/16189,
where the test was failing as we expect parent of fan to be present, but
for fans under fabric modules, fabric modules were not present in `STATE_DB`.
Added a unit-test which tests whether `PHYSICAL_ENTITY_INFO` is updated
when a fabric module is inserted.
Also, tested …

chassisd: add fabric module information to STATE_DB

---

sonic-chassisd/scripts/chassisd

For SmartSwitch platform the module history files were getting stored with txt extension, where as they should have been stored with json extension.  Now storing the history files with json extension.
Fixed issue: #22072
The process-reboot-cause expects the reboot_cause history files to be stored with json extension.
Unit Test on a SmartSwitch:
root@MtFuji:/home/cisco# cd /host/reboot-cause/module/dpu6
root@MtFuji:/host/reboot-cause/module/dpu6# ls -lrt
total 12
-rw-r--r-- 1 root root   40 Apr  4 07:56 reboot-cause.txt
lrwxrwxrwx 1 root root   76 Apr  4 07:56 previous-reboot-cause.json -> /host/reboot-cause/module/dpu6/history/2025_04_04_07_56_45_reboot_cause.json
drwxr-xr-x 2 root root 4096 Apr  4 07:56 history
root@MtFuji:/host/reboot-cause/module/dpu6# cd history/ …

Store reboot_cause history files with json extension. Fix for #22072 

---

sonic-xcvrd/xcvrd/xcvrd.py

Depends on https://github.com/sonic-net/sonic-platform-common/pull/564
Ignore time wait in `cmis.set_lpmode`
In `CmisManagerTask`, it calls `cmis.set_lpmode` for each logical port. The time wait causes a `wait_time * num_of_logical_port` delay in link up time. The PR is to optimize it.
Manual test
unit test

[xcvrd] do not wait state change while calling cmis.set_lpmode

---

sonic-xcvrd/tests/mock_swsscommon.py
sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

1. Use hget instead of hgetall to gain better performance
2. Optimize `SfpStateUpdateTask.init`:
- Use cache in this function for different logical ports with the same physical module. 
- Handles transceiver info table and media settings before any other table.
Improve module initialization performance. Due my test:
1. `hget` is 7 times faster than `hgetall` when getting cmis module state
2. Before optimizing `SfpStateUpdateTask.init`, the last module takes about 5 minutes to finish `notify_media_settings` call; after the optimization, the last module takes about 1 minutes to finish notify_media_settings` call.
Manual test

[xcvrd] Optimize module initialization performance

---

sonic-pcied/scripts/pcied
sonic-pcied/tests/mocked_libs/sonic_platform/pcie.py
sonic-pcied/tests/test_DaemonPcied.py
sonic-pcied/tests/test_pcied.py

This PR introduces comprehensive exception handling throughout the pcied daemon script to enhance reliability and ensure graceful handling of runtime errors. Key improvements include:
- Try-except blocks added around critical operations
- Fix variables during logging.
These changes make the daemon more resilient during unexpected conditions for REDIS DB disconnection or returning an exception.
- Replace the daemon in a test-bed
- Inject redis-server crash
- Observe any crashes occurred for PCIe daemon.
- With the changes, only observe following exception but no crashes in PCIe daemon:
2025 Jun 10 22:26:51.529324 XXX ERR pmon#pcied[4197]: Exception while checking AER attributes for ff:13.2: RedisError: Failed to redisGetReply in RedisPipeline::pop, err=3: errstr=Server closed the …

Add Robust Exception Handling to pcied Daemon for Improved Stability

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassisd.py
sonic-chassisd/tests/test_dpu_chassisd.py

Change was done so that the DPU states are updated on the following conditions:
`midplane_state` -> The switch erases the `DPU_STATE` table when the midplane state changes to down, So as to remove the stale states of control plane and data plane
`control_plane_state` and `data_plane_state` Subscribe to the `DPU_STATE` table, if there is an update, where only `midplane_state` is updated to the table, (meaning there is no control plane or data plane state present in the table). Then update the states back to the table, (If DPUs are online, this means that the states have been removed by switch
Set midplane interface to down on DPU:
`ifconfig eth0-midplane down` -> Observe that control plane and dataplane states are set to down
`ifconfig eth0-midplane up` -> Observe that control plane and …

[Smartswitch] Fix incorrect reporting of data plane and control plane by DPU

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/test_chassis_db_init.py
sonic-chassisd/tests/test_chassisd.py

Chassisd does not wait for the execution to complete for previous admin state change requests. Fixed issue #22138
Fixed issue #22138
Chassisd does not wait for the execution to complete for previous admin state change requests. Added support to solve this.
The corresponding sonic-utilities PR is: https://github.com/sonic-net/sonic-utilities/pull/3937
Added a state to indicate the progress of an admin_state transition period (window) of every module in config_db.
When in progress do not allow another admin_state change for that module.
Mark the beginning of state transition in the CLI itself. Added a timeout also for error cases.
Mark the end of state transition in chassisd
ssue "config chassis module startup DPU0". This takes around 3 mins. Check the config_db and verify the new variable …

Chassisd does not wait for the execution to complete for previous admin state change requests. Fixed issue #22138

---

sonic-pcied/scripts/pcied
sonic-pcied/tests/test_DaemonPcied.py

Two changes are being done in this PR:
Remove deletion of the `PCIE_DETACH_INFO` from the pcied (This should be handled by the power off/power on of the DPU from the module_base implementation)
The returned value from `self.detach_info.get(key)` in pcied is of the form tuple:
`(True, [('bus_info', '0000:03:00.1'), ('dpu_state', 'detaching')])` This has to be handled correctly by the pcied (which was expecting a dictionary 
This is required since the pcied should not delete the entries from the `PCIE_DETACH_INFO` table as opposed to the module_base implementation
Unit tests:
```
tests/test_DaemonPcied.py::TestDaemonPcied::test_signal_handler PASSED   [  7%]
tests/test_DaemonPcied.py::TestDaemonPcied::test_run PASSED              [ 14%]
tests/test_DaemonPcied.py::TestDaemonPcied::test_del …
```

[Smartswitch][pcied] Fix pcied handling for smartswitch during DPU detach #5

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/sff_mgr.py
sonic-xcvrd/xcvrd/xcvrd.py

HLD: https://github.com/sonic-net/SONiC/pull/1867
- Add xcvrd/sff_mgr support for enabling high power class if module's power class is greater or equal to 5 (Refer to SFF-8636 spec 6.2.6 Control Functions (Page 00h, Bytes 86-99) for byte 93 definition)
Without enabling high power class for those modules, the module won't operate properly with power output and link won't come up.
Verified the module operate with proper power output.

Add high power class support for non-CMIS modules in xcvrd

---

sonic-xcvrd/xcvrd/sff_mgr.py

The logger object may be different based on subsystem but not all have the same log callbacks leading to errors in SffLogger:
```
2025 Jun 26 10:25:14.640757 dvc140 ERR pmon#xcvrd[120]:     self.logger.log_info("subscribing to port_tbl {} - {} DB of namespace {} ".format(
2025 Jun 26 10:25:14.640793 dvc140 ERR pmon#xcvrd[120]:     ^^^^^^^^^^^^^^^^^^^^
2025 Jun 26 10:25:14.640793 dvc140 ERR pmon#xcvrd[120]: AttributeError: 'SffLoggerForPortUpdateEvent' object has no attribute 'log_info'
```
This patch adds log_info to Sff.
Fix crash after #567 was merged
Reproduced on physical hardware

xcvrd: sff_mgr missing log_info leading to crashes

---

sonic-sensormond/scripts/sensormond
sonic-sensormond/tests/test_sensormond.py

Two quality of life improvements for sensormond:
1. Allow for the user to configure timeout for printing time log warning (keep default at 30), this is set in the the platform_env.conf through the `SENSORMOND_WARNING_TIME` value
2. Cascade stop events (from signal handler) into voltage and current updaters to allow for more graceful checking _during_ the update process, current setup has 10 second timeout and given the updaters can take some time to run can result in SIGKILLs getting sent during operations.
With a lot of sensors, the logs can be filled with warnings about exceeding the time to read even if it is expected by the vendor. Additionally, with this longer time, the SIGTERM can not be checked in enough time before supervisorctl falls back to using a SIGKILL
Tested on Cisco …

Sensormond changes to support configurable time for logging threshold and better handling of fatal signals

---

sonic-pcied/scripts/pcied

The pcie_dev string was incorrectly using an f-string-style format without the f prefix or .format() usage, resulting in the placeholder being treated as a literal string. As a result, the PCIe device name was not being correctly computed and logged, which affects DPU detach warnings and related debugging.
PCIe device name not logged correctly during DPU detachment scenarios. This change fixes the formatting using the str.format() method, ensuring the PCIe device address is constructed accurately. As a result, the correct device name will now appear in logs, aiding in proper debugging and tracking.
Tested and verified in my local testbed
tests/test_DaemonPcied.py::TestDaemonPcied::test_check_pcie_devices_detaching PASSED 
Also, to manually simulate a pass scenario and verify correct PCIe …

Fix incorrect string formatting for PCIe device name

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Fix for : https://github.com/sonic-net/sonic-buildimage/issues/21603
Add a logic to decommission data path by setting Appl Sel 0 using the existing CMIS SM. 
When there are multiple subports/logical ports under the same physical port:
1. For lead logical port of decommission (whoever is the first one calling is_decomm_required()==True), it will conduct the actual decommission state machine.
2. For non-lead logical port(s), it will wait until the decommission state machine is done by the lead logical port.
The non-lead port will remain in the CMIS inserted state until the lead port completes the decommissioning or it transitions to Failed state.
Decommission lanes of the port which doesn't has required AppCode set to default
```
2025 Apr 30 23:16:01.293831 sonic NOTICE pmon#xcvrd[27]: …
```

Add CMIS FSM for DP decomission

---

sonic-xcvrd/tests/test_xcvrd.py

If the CPU of build server is very fast, testcase `test_CmisManagerTask_task_worker_decommission` might have a chance to fail at https://github.com/sonic-net/sonic-platform-daemons/blob/d555defff9b9b1dd7727340055f8cd908188670f/sonic-xcvrd/tests/test_xcvrd.py#L3441
The reason is:
- Test code incorrectly assumes `update_cmis_state_expiration_time(lport, duration_seconds=0.0)` will set `cmis_expired` as current_time (i.e. current_time + `0.0`, meaning expired immediately), however there's always a `CMIS_EXPIRATION_BUFFER_MS` (`2ms`) getting added on top of it.
https://github.com/sonic-net/sonic-platform-daemons/blob/d555defff9b9b1dd7727340055f8cd908188670f/sonic-xcvrd/xcvrd/xcvrd.py#L1084-L1094
e.g. if current_time is `01:36:25.528`, calling `self.update_cmis_state_expiration_time(lport, …

Fix rare timing issue in test_CmisManagerTask_task_worker_decommission

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

Update chassisd to add fabric card module information to `PHYSICAL_ENTITY_INFO` table in `STATE_DB`  only if the module is present.
Fixes [#23372](https://github.com/sonic-net/sonic-buildimage/issues/23372)
Run `sonic-db-cli STATE_DB keys "PHYSICAL_ENTITY_INFO|FABRIC*`"`
It should only list the fabric card modules that are present.

[chassis] modify chassisd to add fabric card information to PHYSICAL_ENTITY_INFO table only if module is present

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

SmartSwitch - Reboot cause for DPUs not updated on complete system reboot
SmartSwitch - Reboot cause for DPUs not updated on complete system reboot
Fixes #22430  https://github.com/sonic-net/sonic-buildimage/issues/22430
In melanox smartswitch platforms the reboot-cause is not persisted and updated into db after a complete switch reboot
Issued system level reboot and checked the CLI "show reboot-cause all" and "show reboot-cause history DPU4" output.
This reflects the reboot.
root@sonic:/home/cisco# show reboot-cause all
Device    Name                 Cause                Time                             User
--------  -------------------  -------------------  -------------------------------  ------
NPU       2025_06_25_21_17_01  reboot               Wed Jun 25 09:09:00 PM UTC 2025  cisco …

Fix for 22430 - SmartSwitch - Reboot cause for DPUs not updated on complete system reboot

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_chassisd.py

This PR fixes some changes from : https://github.com/sonic-net/sonic-buildimage/issues/23602
Changes done:
- Use of `ModuleTransitionFlagHelper` class for modification of the transition flags, this class recreates a new DBConnector when the class is initialized,  
- `MODULE_PRE_SHUTDOWN` should be applied either way even if DPU is not powering off on startup, this is required because we need to add PCIE entries on Dark mode system startup -> DPU is powered off but STATE_DB entries need to be present
-  Addition of `return fvs.get(CHASSIS_MODULE_INFO_OPERSTATUS_FIELD, ModuleBase.MODULE_STATUS_EMPTY)` This is done because the transition flag is added first to the CHASSIS_MODULE_TABLE, (and it is queried to check if OPER_STATUS and other fields are present. if the oper_status is not present …

[Smartswitch] Fix chassisd to prevent crashes on smartswitch

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

This PR improves the logging in the optics SI parser to provide better diagnostic information when unable to find an appropriate match for optic SI settings for a physical port.
The previous log message was an error which is misleading since there can be genuine cases wherein optics SI settings are not present for a module.
Hence, changing the log level to INFO and adding more debug data.
Testing is in progress currently
MSFT ADO - 34731836

[xcvrd] Improve logging in case of unable to find appropriate match for optic SI settings

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/optics_si_parser.py

202505 cherry-pick for https://github.com/sonic-net/sonic-platform-daemons/pull/672
This PR improves the logging in the optics SI parser to provide better diagnostic information when unable to find an appropriate match for optic SI settings for a physical port.
The previous log message was an error which is misleading since there can be genuine cases wherein optics SI settings are not present for a module.
Hence, changing the log level to INFO and adding more debug data.
Verified
MSFT ADO - 34731836

[202505] [xcvrd] Improve logging in case of unable to find appropriate match for optic SI settings (#672)

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

Handle restore_count and system_enable ”NoneType“ value scenario.
SFP didn't come back when system_enable is NoneType and run into failure.
```
root@str-msn2700-20:/tmp# cat test.py
#!/usr/bin/env python3
from swsscommon import swsscommon
def get_state_db():
return swsscommon.DBConnector("STATE_DB", 0)
def is_syncd_warm_restore_complete(restore_count, system_enabled):
try:
if restore_count is not None:
if isinstance(restore_count, int):
if restore_count > 0:
return True
elif isinstance(restore_count, str):
if restore_count.strip().isdigit() and int(restore_count.strip()) > 0:
return True
if isinstance(system_enabled, str):
if system_enabled.strip().lower() == "true":
return True
except Exception as e:
print(f"[WARN] Unexpected value: restore_count={restore_count}, …
```

Handle restore_count and system_enable ”NoneType“ value scenario.

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/test_dpu_chassisd.py

Main Logic Addition (sonic-chassisd/scripts/chassisd): Added a new condition check in the DpuStateManagerTask class The logic checks if there's a non-empty key AND the database is not 'CHASSIS_STATE_DB' When both conditions are true, it sets update_required = True and breaks out of the loop 
When there is updates to multiple DBs at the same time, usually if there is update to CHASSIS_STATE_DB the update_required is set to false, this change is added to handle this case 
``` tests/test_dpu_chassisd.py::test_dpu_state_manager_update_required_logic PASSED [100%] ``` 
Manual test to shutdown interface/service and confirm that the data plane/control plane interfaces are set to down

[Smartswitch][DPU]Add multiple key handling
