README.md
sonic-ledd/scripts/ledd
sonic-ledd/setup.py
sonic-ledd/sonic_led/led_control_base.py

Add sonic-ledd (Front-panel LED control daemon)

---

sonic-ledd/scripts/ledd

platform plugins is mounted to /usr/share/sonic/platform/plugins in pmon docker

fix platform plugin location for ledd in pmon docker

---

sonic-ledd/scripts/ledd

Refactor ledd such that it no longer periodically polls for interface status changes, and instead subscribes to interface status changes from APPL_DB.

[ledd] Now subscribe to notifications from APPL_DB rather than polling

---

sonic-xcvrd/scripts/xcvrd

This PR extend the xcvrd to post more information to the state_db.
Detail info please refer to the design doc: https://github.com/Azure/SONiC/blob/master/doc/pmon/pmon-enhancement-design.md
This PR has a **dependency** on https://github.com/Azure/sonic-platform-common/pull/22

Xcvrd extention to post more info to the DB

---

sonic-psud/scripts/psud

What and how I did:
1. Get PSU information such as presence status, power status, temperature and so on periodically
2. Set LED color and trigger syslog according to PSU information
3. Store LED color to database for command line use
How I verify:
1. Manual test on Spectrum1, Spectrum2
2. Add/adjust test cases in sonic-mgmt

[psud] Enhancement for PSU led management

---

sonic-thermalctld/scripts/thermalctld

**Resolved issue**: The warning status is invalid after updating temperature status
**Solution**:  Changed warning status update condition
**Signed-off-by**: Wirut Getbamrung wgetbumr@celestica.com

[thermalctld] Fix invalid warning status

---

sonic-ledd/scripts/ledd
sonic-psud/scripts/psud
sonic-syseepromd/scripts/syseepromd
sonic-thermalctld/scripts/thermalctld
sonic-xcvrd/scripts/xcvrd

* Should use new multiDB Connector in daemon base
* This submodule needs updated with daemon_base changes together which is in sonic_buildinage
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

[MultiDB] should use multiDB API

---

sonic-xcvrd/scripts/xcvrd

Update key names which were missed in https://github.com/Azure/sonic-platform-daemons/pull/62
Fixes https://github.com/Azure/sonic-buildimage/issues/4886

[xcvrd] Update key names in 'get_media_settings_value()'

---

sonic-ledd/scripts/ledd
sonic-psud/scripts/psud
sonic-thermalctld/scripts/thermalctld

Remove unused imports to fix LGTM alerts

Remove unused imports

---

sonic-thermalctld/scripts/thermalctld
sonic-thermalctld/tests/test_thermalctld.py

Each class which requires logging now inherits from sonic-py-common.logger.Logger

Proper fix for thermalctld using sonic-py-common

---

sonic-pcied/scripts/pcied

Fix the bug : https://github.com/Azure/sonic-buildimage/issues/5236

Remove sonic-utilities dependency from pcied

---

sonic-ledd/scripts/ledd
sonic-xcvrd/scripts/xcvrd

Commit the Multi-asic changes commit (PR #64 ) into 201911.

[201911] [ledd] [xcvrd] Multi-asic changes in platform daemons

---

sonic-psud/scripts/psud

Fix `Failed to update PSU data - global name 'self' is not defined` 
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

[psud] Fix psud logging

---

azure-pipelines.yml

Call pip2/3 using sudo to ensure packages are installed globally.

[ci] Call pip2/3 using sudo

---

.github/pull_request_template.md

Add GitHub pull request template

[GitHub] Add pull request template

---

azure-pipelines.yml

What I did
fix python gcov warning "Please install dotnet core to enable automatic generation of Html report"
more info check: Azure/sonic-snmpagent#215
How I did it
install dotnet core
How to verify it

[python coverage]fix result color bar

---

sonic-xcvrd/xcvrd/xcvrd.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Removed undefined symbol 'sfp_status_helper'. This came from cherry-pick commit:-
https://github.com/Azure/sonic-platform-daemons/commit/1cf5996505e013bdbce243cb0e4f7f1ee8be9f94

Removed undefined symbol 'sfp_status_helper'

---

sonic-xcvrd/tests/test_xcvrd.py

Signed-off-by: Prince George <prgeor@microsoft.com>
Added unit test for transceiver OIR events
Added unit test for changes done in PR:- 
https://github.com/Azure/sonic-platform-daemons/pull/201/
Unit test passes

Added unit test for sfp oir events

---

sonic-xcvrd/xcvrd/xcvrd_utilities/y_cable_helper.py

This PR creates unknown entries for muxcable in case a cable is present in the port but is not one of the existing Y-Cable vendors. This is particularly a corner case where in indeed while muxcable initiation there is a cable which is not a `True` y-cable but a generic cable and we still want to see this entry be created as an unknown. 
Improve the initiation logic for Y-Cable
Ran the changes on the pmon container.

[Y-Cable] create unknown entries for mux_cable when there is a cable present but module definition is not present

---

azure-pipelines.yml

Enable Diff Coverage for sonic-platform-daemons

Enable Diff Coverage for sonic-platform-daemons

---

azure-pipelines.yml

Fix python wheels path reference in sonic image.

Fix python wheels path from vs official build.

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR fixes some syntax warnings for ycabled.
remove some syntax warnings
UT coverage would test the change

[ycabled] Fix some syntax warnings in ycabled

---

sonic-ycabled/ycable/ycable_utilities/y_cable_helper.py

This PR is meant to fix gRPC keepalive timeout values. With this change and adding the options to server side, the pings start working for TCP connection for all gRPC channels. This PR is also meant to increase the time intervals between pings to 4 seconds for gRPC connections
With this change the TCP connections are always persistent
example:
```
admin@sonic:~$ netstat | grep 50075
tcp6       0      0 tmg.dtap.sphybrid:41828 vlan2003.mim-a75s:50075 ESTABLISHED
tcp6       0      0 tmg.dtap.sphybrid:43912 192.168.0.3:50075       ESTABLISHED
tcp6       0      0 tmg.dtap.sphybrid:43620 win-cfr7mesbc6v.c:50075 ESTABLISHED
tcp6       0      0 192.168.0.1:37768       192.168.0.23:50075      ESTABLISHED
tcp6       0      0 tmg.dtap.sphybrid:58776 win-cfr7mesbc6v.c:50075 ESTABLISHED
tcp6       0 …
```

[ycabled][grpc] Fix some time interval,options for grpc keep alive to work

---

sonic-xcvrd/xcvrd/xcvrd.py

Fix issue: function requires 4 parameters. but only 3 given
Fix issue: function requires 4 parameters. but only 3 given
Manual test

Fix typo in xcvrd

---

sonic-thermalctld/scripts/thermalctld
sonic-xcvrd/tests/test_xcvrd.py

Remove TODO comments which are no longer needed
Remove TODO comments which are no longer needed
Only comment change

Remove TODO comments which are no longer needed

---

sonic-chassisd/scripts/chassisd
sonic-chassisd/tests/mock_swsscommon.py
sonic-chassisd/tests/mocked_libs/sonic_platform/__init__.py
sonic-chassisd/tests/mocked_libs/sonic_platform/chassis.py
sonic-chassisd/tests/mocked_libs/sonic_platform/platform.py
sonic-chassisd/tests/test_chassisd.py

Double commit of PR : https://github.com/sonic-net/sonic-platform-daemons/pull/328 in master --> 202205 branch

[202205] Chassisd do an explicit stop of the config_manager

---

azure-pipelines.yml

Migrate agent pool to sonic-common to fix 'No space left on device' issue.

[ci] Migrate agent pool to self hosted pool

---

azure-pipelines.yml

Update the code coverage rate to 80%

Update the code coverage rate to 80%

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd.py

We are currently planning move the "active_firmware" and "inactive_firmware" fields from TRANSCEIVER_INFO table to TRANSCEIVER_FIRMWARE_INFO table.
MSFT ADO - 26788447
The changes in this PR should be merged along with https://github.com/sonic-net/sonic-platform-common/pull/440 and https://github.com/sonic-net/sonic-mgmt/pull/11708
Both active and inactive firmware version fields can dynamically change during firmware upgrade unlike other fields in TRANSCEIVER_INFO table which are static.
Hence, we are planning to create a separate table to store the firmware version so that these fields can be updated periodically by DomInfoTaskUpdate thread. A separate PR will be raised to enable polling of firmware version fields by DomInfoTaskUpdate thread.
A separate PR is planned to be created for …

Move firmware version fields to TRANSCEIVER_FIRMWARE_INFO table

---

azure-pipelines.yml

Fix no space left on device issue.
Fix buster-backports issue in debian repo.

[ci] Fix 202205 pipeline issue.

---

sonic-xcvrd/tests/test_xcvrd.py
sonic-xcvrd/xcvrd/xcvrd_utilities/media_settings_parser.py

Manual cherry-pick for #533 to 202311 due to conflicts

Improve parsing of media-settings.json for non-CMIS and breakout ports (#533)

---

sonic-thermalctld/scripts/thermalctld

Creating DC of https://github.com/sonic-net/sonic-platform-daemons/pull/640 for 202505
Bringing fix for https://github.com/sonic-net/sonic-platform-daemons/pull/640 into 202505

Fix physical entity tables in statedb to account for modified psu key naming - 202505 DC
